#!/bin/sh
# postinst script for Wazuh-dashboard
# Copyright (C) 2015-2022, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

set -e

export NAME=wazuh-dashboard
export CONFIG_DIR=/etc/""${NAME}""
export INSTALLATION_DIR=/usr/share/"${NAME}"
export LOG_DIR=/var/log/"${NAME}"
export PID_DIR=/run/"${NAME}"


# Setting Owner and group of own folders
mkdir -p ${PID_DIR}
mkdir -p ${LOG_DIR}
chown -R "${NAME}":"${NAME}" "${PID_DIR}"
chown -R "${NAME}":"${NAME}" "${CONFIG_DIR}"
chown -R "${NAME}":"${NAME}" "${INSTALLATION_DIR}"
chown -R "${NAME}":"${NAME}" "${LOG_DIR}"
chown -R "${NAME}":"${NAME}" /etc/default/"${NAME}"
chown -R "${NAME}":"${NAME}" /etc/systemd/system/"${NAME}"
chmod 750 /etc/systemd/system/wazuh-dashboard
chmod 750 /etc/default/wazuh-dashboard
chmod 640 "${CONFIG_DIR}"/dashboard.yml
chmod 750 "${CONFIG_DIR}"/certs
chmod 400 "${CONFIG_DIR}"/certs/*
chmod 640 "${CONFIG_DIR}"/node.options
chmod 640 /etc/systemd/system/wazuh-dashboard.service
find "${INSTALLATION_DIR}" -type d -exec chmod 750 {} \;
find "${INSTALLATION_DIR}" -type f -perm 644 -exec chmod 640 {} \;
find "${INSTALLATION_DIR}" -type f -perm 755 -exec chmod 750 {} \;


case "$1" in
    configure)
        setcap 'cap_net_bind_service=+ep' "${INSTALLATION_DIR}"/node/bin/node
        if [ -f "${INSTALLATION_DIR}"/"${NAME}".restart ]; then
        rm -f "${INSTALLATION_DIR}"/"${NAME}".restart
            if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 ; then
                systemctl daemon-reload > /dev/null 2>&1
                systemctl restart wazuh-dashboard.service > /dev/null 2>&1
            elif command -v service > /dev/null 2>&1 && service wazuh-dashboard status 2>/dev/null | grep "running" > /dev/null 2>&1; then
                service wazuh-dashboard restart > /dev/null 2>&1
            fi
        fi

    ;;


    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
