#!/bin/sh
# preinst script for wazuh-dashboard

set -e

#
# This script is executed in the pre-installation phase
#
#   On Debian,
#       $1=install : indicates an new install
#       $1=upgrade : indicates an upgrade
#
#   On RedHat,
#       $1=1       : indicates an new install
#       $1=2       : indicates an upgrade

# configuration variables
export NAME=wazuh-dashboard
export CONFIG_DIR=/etc/${NAME}
export INSTALLATION_DIR=/usr/share/${NAME}
export LOG_DIR=/var/log/${NAME}

# environment configuration
if [ ! -d ${INSTALLATION_DIR} ]; then
    mkdir -p ${CONFIG_DIR}
    mkdir -p ${INSTALLATION_DIR}
    mkdir -p ${LOG_DIR}

else
    rm -rf ${INSTALLATION_DIR}
    mkdir -p ${INSTALLATION_DIR}
    rm -rf ${CONFIG_DIR}
    mkdir -p ${CONFIG_DIR}
    rm -rf ${LOG_DIR}
    mkdir -p ${LOG_DIR}
fi

case "$1" in
    # Debian ####################################################
    install|upgrade)

        # Create wazuh-indexer group if not existing
        if ! getent group ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} group..."
            addgroup --quiet --system ${NAME}
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --home /nonexistent \
                    --ingroup ${NAME} \
                    --disabled-password \
                    --shell /bin/false \
                    ${NAME}
            echo " OK"
        fi

        # Stop the services to upgrade the package
        if [ $1 = 2 ]; then
        if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet ${NAME} > /dev/null 2>&1; then
            systemctl stop ${NAME}.service > /dev/null 2>&1
            touch ${INSTALLATION_DIR}/${NAME}.restart
        # Check for SysV
        elif command -v service > /dev/null 2>&1 && service ${NAME} status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
            service ${NAME} stop > /dev/null 2>&1
            touch ${INSTALLATION_DIR}/${NAME}.restart
        fi
        fi
    ;;
    abort-deconfigure|abort-upgrade|abort-remove)
    ;;

    # RedHat ####################################################
    1|2)

        # Create wazuh-indexer group if not existing
        if ! getent group ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} group..."
            groupadd -r ${NAME}
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} user..."
            useradd --system \
                    --no-create-home \
                    --home-dir /nonexistent \
                    --gid ${NAME} \
                    --shell /sbin/nologin \
                    --comment "${NAME} user" \
                    ${NAME}
            echo " OK"
        fi

        # Stop the services to upgrade the package
        if [ $1 = 2 ]; then
        if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet ${NAME} > /dev/null 2>&1; then
            systemctl stop ${NAME}.service > /dev/null 2>&1
            touch ${INSTALLATION_DIR}/${NAME}.restart
        # Check for SysV
        elif command -v service > /dev/null 2>&1 && service ${NAME} status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
            service ${NAME} stop > /dev/null 2>&1
            touch ${INSTALLATION_DIR}/${NAME}.restart
        fi
        fi
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
