#!/bin/sh
# postrm script for Wazuh 
# Wazuh, Inc 2015-2020
set -e
DIR="/var/ossec"
WAZUH_TMP_DIR="/tmp/wazuh-manager"

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)


    # Fix for forcing the stop of the api
    if ps aux | grep ${DIR}/api/app.js | grep -v grep; then
        kill -9 `ps -ef | grep "${DIR}/api/app.js" | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
    fi

  	if getent passwd | grep -q "^ossecr" ; then
  		deluser ossecr  > /dev/null 2>&1
  	fi
  	if getent passwd | grep -q "^ossecm" ; then
  		deluser ossecm  > /dev/null 2>&1
  	fi
  	if getent passwd | grep -q "^ossec" ; then
  		deluser ossec  > /dev/null 2>&1
  	fi
  	if getent group | grep -q "^ossec" ; then
  		delgroup ossec  > /dev/null 2>&1
  	fi

    if [ -f /etc/logrotate.d/wazuh-hids ]; then
      rm -f /etc/logrotate.d/wazuh-hids
    fi

    if [ -f /etc/ossec-init.conf ]; then
        rm -f /etc/ossec-init.conf
    fi

    if [ -d ${WAZUH_TMP_DIR} ]; then
        rm -rf ${WAZUH_TMP_DIR}
    fi

	update-rc.d -f wazuh-manager remove

    ;;


    upgrade)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

    ;;

esac

exit 0
