#!/bin/sh
# prerm script for wazuh-manager

set -e

case "$1" in
    upgrade|deconfigure)
      if [ -f /var/ossec/bin/ossec-control ]; then
         /var/ossec/bin/ossec-control stop > /dev/null 2>&1
      fi

    ;;

    remove)

      if [ -n "$(ps -e | grep -E ^\ *1\ .*systemd$)" ]; then
        systemctl stop wazuh-manager
      fi

      if [ -n "$(ps -e | grep -E ^\ *1\ .*init$)" ]; then
        service wazuh-manager stop
      fi

      if [ -f /var/ossec/bin/ossec-control ]; then
        /var/ossec/bin/ossec-control stop > /dev/null 2>&1
      fi

      # Purging files
      rm -rf /var/ossec/etc/*
      rm -rf /var/ossec/stats/*
      rm -rf /var/ossec/logs/*
      rm -rf /var/ossec/queue/*
      rm -rf /var/ossec/var/*
      rm -rf /var/ossec/framework/*

    ;;

    failed-upgrade)
      if [ -f /var/ossec/bin/ossec-control ]; then
	       /var/ossec/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;

esac

exit 0
