rpm -ivh --force --ignorearch --nodeps \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/iproute-4.11.0-25.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dhclient-4.2.5-77.el7.centos.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/audit-libs-python-2.8.5-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/audit-libs-2.8.5-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/autoconf-2.69-11.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/automake-1.13.4-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bash-4.2.46-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/binutils-2.27-41.base.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bison-3.0.4-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bluez-libs-devel-5.44-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bluez-libs-5.44-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bzip2-devel-1.0.6-13.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bzip2-libs-1.0.6-13.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bzip2-1.0.6-13.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ca-certificates-2018.2.22-70.0.el7_5.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/checkpolicy-2.5-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/chkconfig-1.7.4-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/coreutils-8.22-24.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/cpio-2.11-27.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/cpp-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/desktop-file-utils-0.23-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/diffutils-3.3-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dracut-network-033-564.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dracut-033-564.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dwz-0.11-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/e2fsprogs-devel-1.42.9-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/e2fsprogs-libs-1.42.9-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/elfutils-devel-0.176-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/elfutils-libelf-devel-0.176-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/elfutils-libelf-0.176-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/elfutils-libs-0.176-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/elfutils-0.176-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/emacs-filesystem-24.3-22.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ethtool-4.8-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/expat-devel-2.1.0-10.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/expat-2.1.0-10.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/file-devel-5.11-35.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/file-libs-5.11-35.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/file-5.11-35.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/findutils-4.5.11-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/fipscheck-lib-1.4.1-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gawk-4.0.2-4.el7_3.1.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gcc-c++-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gcc-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gdb-7.6.1-115.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gdbm-devel-1.10-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gdbm-1.10-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gettext-libs-0.19.8.1-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gettext-0.19.8.1-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/git-1.8.3.1-20.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glib2-2.56.1-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glibc-devel-2.17-292.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glibc-headers-2.17-292.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glibc-2.17-292.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gmp-devel-6.0.0-15.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gmp-6.0.0-15.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gnupg2-2.0.22-5.el7_5.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/grep-2.20-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gzip-1.5-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/info-5.1-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/json-glib-1.4.2-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/kexec-tools-2.0.15-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/krb5-devel-1.15.1-37.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/updates/armhfp/Packages/krb5-libs-1.15.1-37.el7_7.2.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/less-458-9.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libX11-devel-1.6.7-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libX11-1.6.7-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXft-devel-2.3.2-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libacl-devel-2.2.51-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libacl-2.2.51-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libappstream-glib-0.7.8-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libarchive-devel-3.1.2-12.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libarchive-3.1.2-12.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libassuan-2.1.0-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libattr-devel-2.4.46-13.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libattr-2.4.46-13.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcap-2.22-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcgroup-0.41-21.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcom_err-devel-1.42.9-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcom_err-1.42.9-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcroco-0.6.12-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcurl-7.29.0-54.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libdb-devel-5.3.21-25.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libdb-5.3.21-25.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libedit-3.0-12.20121213cvs.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libffi-devel-3.0.13-18.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libffi-3.0.13-18.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgcab1-0.7-4.el7_4.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgcc-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgcrypt-devel-1.5.3-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgcrypt-1.5.3-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgomp-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgpg-error-devel-1.12-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libgpg-error-1.12-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libicu-50.2-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libmpc-1.0.1-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libselinux-python-2.5-14.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libselinux-2.5-14.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libsemanage-python-2.5-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libsepol-2.5-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libsoup-2.62.2-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libstdc++-devel-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libstdc++-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libtirpc-devel-0.2.4-0.16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libtirpc-0.2.4-0.16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libtool-2.4.2-22.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libunistring-0.9.3-9.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libuuid-devel-2.23.2-61.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libuuid-2.23.2-61.el7.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/libuv/1.34.0-1.el7/armv7hl/libuv-1.34.0-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxcb-devel-1.13-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxml2-devel-2.9.1-6.el7_2.3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxml2-python-2.9.1-6.el7_2.3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxml2-2.9.1-6.el7_2.3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/lua-5.1.4-15.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/lzo-devel-2.06-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/lzo-minilzo-2.06-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/lzo-2.06-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/m4-1.4.16-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/make-3.82-24.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/man-db-2.6.3-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/mpfr-3.1.1-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ncurses-devel-5.9-14.20130511.el7_4.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ncurses-libs-5.9-14.20130511.el7_4.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/nodejs/6.17.1-1.el7/armv7hl/nodejs-6.17.1-1.el7.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/nodejs/6.17.1-1.el7/armv7hl/npm-3.10.10-1.6.17.1.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nspr-devel-4.21.0-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nspr-4.21.0-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-devel-3.44.0-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-pem-1.0.3-7.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-softokn-devel-3.44.0-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-softokn-3.44.0-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-sysinit-3.44.0-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-util-devel-3.44.0-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-util-3.44.0-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-3.44.0-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/openldap-2.4.44-21.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/openssh-clients-7.4p1-21.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/openssh-7.4p1-21.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/openssl-devel-1.0.2k-19.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/openssl-libs-1.0.2k-19.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pam-1.1.8-22.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/patch-2.7.1-11.el7.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/patchelf/0.9-10.el7/armv7hl/patchelf-0.9-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pcre-8.32-17.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Carp-1.26-244.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Data-Dumper-2.145-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Error-0.17020-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Exporter-5.68-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-File-Path-2.09-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-File-Temp-0.23.01-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Getopt-Long-2.40-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Git-1.8.3.1-20.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-PathTools-3.40-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-TermReadKey-2.30-20.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Test-Harness-3.28-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Text-ParseWords-3.29-4.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Thread-Queue-3.02-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-constant-1.27-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-srpm-macros-1-8.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-threads-1.87-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-5.16.3-294.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pinentry-0.8.1-17.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pkgconfig-0.27.1-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/policycoreutils-python-2.5-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/policycoreutils-2.5-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/popt-devel-1.13-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/popt-1.13-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pth-2.0.7-23.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-IPy-0.75-6.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-kitchen-1.1.1-5.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-libs-2.7.5-86.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-rpm-macros-3-32.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-srpm-macros-3-32.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-2.7.5-86.el7.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/python34/3.4.10-4.el7/armv7hl/python34-libs-3.4.10-4.el7.armv7hl.rpm \
https://armv7.dev.centos.org/repodir/epel-pass-1/python34/3.4.10-4.el7/armv7hl/python34-3.4.10-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/readline-devel-6.2-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/readline-6.2-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/redhat-rpm-config-9.1.0-88.el7.centos.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rpm-build-libs-4.11.3-40.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rpm-build-4.11.3-40.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rpm-devel-4.11.3-40.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rpm-libs-4.11.3-40.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rpm-4.11.3-40.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/rsync-3.1.2-6.el7_6.1.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sed-4.2.2-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/setools-libs-3.3.8-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sharutils-4.13.3-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/snappy-1.1.0-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sqlite-devel-3.7.17-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sqlite-3.7.17-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sudo-1.8.23-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/systemd-219-67.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tar-1.26-35.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tcl-devel-8.5.13-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tcl-8.5.13-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tix-devel-8.4.3-12.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tix-8.4.3-12.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tk-devel-8.5.13-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/tk-8.5.13-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/unzip-6.0-20.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/valgrind-devel-3.14.0-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/valgrind-3.14.0-16.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/vim-minimal-7.4.629-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/xorg-x11-proto-devel-2018.4-1.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/xz-devel-5.2.2-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/xz-libs-5.2.2-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/xz-5.2.2-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/yum-utils-1.1.31-52.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/yum-3.4.3-163.el7.centos.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/zip-3.0-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/zlib-devel-1.2.7-18.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/zlib-1.2.7-18.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/fipscheck-1.4.1-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libatomic-4.8.5-39.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/jasper-1.900.1-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/jasper-devel-1.900.1-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/jasper-libs-1.900.1-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/jasper-utils-1.900.1-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/kernel-headers-4.19.72-300.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glibc-common-2.17-292.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/keyutils-libs-devel-1.5.8-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/krb5-libs-1.15.1-37.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libmnl-1.0.3-7.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/iptables-1.4.21-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/iptables-devel-1.4.21-33.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/hostname-3.13-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/initscripts-9.49.47-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dhcp-4.2.5-77.el7.centos.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dhcp-devel-4.2.5-77.el7.centos.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dhcp-libs-4.2.5-77.el7.centos.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dhcp-common-4.2.5-77.el7.centos.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bind-export-devel-9.11.4-9.P2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/bind-export-libs-9.11.4-9.P2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libkadm5-1.15.1-37.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libselinux-2.5-14.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libselinux-devel-2.5-14.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libverto-0.2.5-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libverto-devel-0.2.5-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/groff-base-1.22.2-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libX11-common-1.6.7-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxcb-devel-1.13-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXft-2.3.2-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/pkgconfig-0.27.1-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glib-networking-2.56.1-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libxcb-1.13-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/groff-base-1.22.2-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libpipeline-1.2.3-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ncurses-5.9-14.20130511.el7_4.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/ncurses-base-5.9-14.20130511.el7_4.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-softokn-freebl-devel-3.44.0-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/nss-softokn-freebl-3.44.0-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-libs-5.16.3-294.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Scalar-List-Utils-1.27-248.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Pod-Usage-1.63-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Time-Local-1.2300-2.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Pod-Simple-3.28-4.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-threads-shared-1.43-6.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-macros-5.16.3-294.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libjpeg-turbo-1.2.90-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libjpeg-turbo-devel-1.2.90-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libjpeg-turbo-utils-1.2.90-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/freetype-2.8-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/freetype-devel-2.8-14.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/fontconfig-2.13.0-4.3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/fontconfig-devel-2.13.0-4.3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXrender-0.9.10-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXrender-devel-0.9.10-1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXau-1.0.8-2.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXau-devel-1.0.8-2.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Filter-1.49-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Socket-2.010-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Storable-2.45-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Time-HiRes-1.9725-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libselinux-utils-2.5-14.1.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/systemd-libs-219-67.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libglvnd-glx-1.0.1-0.8.git5baa1e5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-libGLU-9.0.0-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-libGLU-devel-9.0.0-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/freeglut-3.0.0-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/freeglut-devel-3.0.0-8.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnetfilter_conntrack-1.0.6-1.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnetfilter_conntrack-devel-1.0.6-1.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnfnetlink-1.0.1-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnfnetlink-devel-1.0.1-4.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/sysvinit-tools-2.88-14.dsf.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcap-devel-2.22-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libcap-2.22-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libsepol-2.5-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libsepol-devel-2.5-10.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnetfilter_conntrack-1.0.6-1.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libnetfilter_conntrack-devel-1.0.6-1.el7_3.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glib2-devel-2.56.1-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/glib2-2.56.1-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gsettings-desktop-schemas-devel-3.28.0-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gsettings-desktop-schemas-3.28.0-2.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gnutls-3.3.29-9.el7_6.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libproxy-0.4.11-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libproxy-devel-0.4.11-11.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-podlators-2.5.1-3.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Pod-Perldoc-3.20-4.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Encode-2.51-7.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/perl-Pod-Escapes-1.04-294.el7_6.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/dejavu-sans-fonts-2.33-6.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/fontpackages-filesystem-1.44-8.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libglvnd-1.0.1-0.8.git5baa1e5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXext-1.3.3-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXext-devel-1.3.3-3.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libglvnd-1.0.1-0.8.git5baa1e5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-libGL-18.3.4-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-libGL-devel-18.3.4-5.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/gl-manpages-1.1-7.20130122.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libICE-1.0.9-9.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/libICE-devel-1.0.9-9.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-devel-2.7.5-88.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-2.7.5-88.el7.armv7hl.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python2-rpm-macros-3-32.el7.noarch.rpm \
http://mirror.centos.org/altarch/7/os/armhfp/Packages/python-libs-2.7.5-88.el7.armv7hl.rpm