#!/bin/sh
# postinst script for wazuh-dashboards
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

set -e

export NAME=wazuh-dashboards
export CONFIG_DIR=/etc/"${NAME}"
export INSTALLATION_DIR=/usr/share/"${NAME}"
export LOG_DIR=/var/log/"${NAME}"
export PID_DIR=/run/"${NAME}"


# Setting Owner and group of own folders
mkdir -p ${PID_DIR}
mkdir -p ${LOG_DIR}
chown -R "${NAME}":"${NAME}" "${LOG_DIR}"
chown -R "${NAME}":"${NAME}" "${PID_DIR}"


case "$1" in
    configure)
        setcap 'cap_net_bind_service=+ep' "${INSTALLATION_DIR}"/node/bin/node
        if [ -f "${INSTALLATION_DIR}"/"${NAME}".restart ]; then
        rm -f "${INSTALLATION_DIR}"/"${NAME}".restart
            if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 ; then
                systemctl daemon-reload > /dev/null 2>&1
                systemctl restart wazuh-dashboards.service > /dev/null 2>&1
            elif command -v service > /dev/null 2>&1 && service wazuh-dashboards status 2>/dev/null | grep "running" > /dev/null 2>&1; then
                service wazuh-dashboards restart > /dev/null 2>&1
            fi
        fi

        runuser "${NAME}" --shell="/bin/bash" --command="${INSTALLATION_DIR}/bin/opensearch-dashboards-keystore create"
        runuser "${NAME}" --shell="/bin/bash" --command="cat ${INSTALLATION_DIR}/config/secret | ${INSTALLATION_DIR}/bin/opensearch-dashboards-keystore add opensearch.username --stdin"
        runuser "${NAME}" --shell="/bin/bash" --command="cat ${INSTALLATION_DIR}/config/secret | ${INSTALLATION_DIR}/bin/opensearch-dashboards-keystore add opensearch.password --stdin"
        rm -f ${INSTALLATION_DIR}/config/secret

    ;;


    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

exit 0
