# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "BraulioV/CentOS-5-i386"
  config.vm.box_version = "1.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 6
  end

  # This script will install all the necessary packages
  # to build the RPM spec in a "chroot directory", compress
  # the directory and build a tar.gz.
  # The tar.gz will be used to create a Docker image from scratch
  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/docker_builder.sh
    /vagrant/docker_builder.sh
  SHELL
end
