#!/bin/sh
# postinst script for wazuh-agent
# Wazuh, Inc 2015-2020

set -e

case "$1" in
    configure)

    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
    DIR="/var/ossec"
    USER="ossec"
    GROUP="ossec"
    WAZUH_GLOBAL_TMP_DIR="${DIR}/packages_files"
    WAZUH_TMP_DIR="${WAZUH_GLOBAL_TMP_DIR}/agent_config_files"
    SCRIPTS_DIR="${WAZUH_GLOBAL_TMP_DIR}/agent_installation_scripts"
    SCA_FILES_DIR="${SCRIPTS_DIR}/sca"

    OSMYSHELL="/sbin/nologin"

    if [ ! -f ${OSMYSHELL} ]; then
        if [ -f "/bin/false" ]; then
            OSMYSHELL="/bin/false"
        fi
    fi

    if ! getent group | grep -q "^ossec" ; then
        addgroup --system ossec > /dev/null 2>&1
    fi
    if ! getent passwd | grep -q "^ossec" ; then
        adduser --system --home ${DIR} --shell ${OSMYSHELL} --ingroup ${GROUP} ${USER} > /dev/null 2>&1
    fi

    ${SCRIPTS_DIR}/gen_ossec.sh init agent ${DIR} > ${DIR}/etc/ossec-init.conf
    chown root:${GROUP} ${DIR}/etc/ossec-init.conf
    chmod 640 ${DIR}/etc/ossec-init.conf

    if [ -z "$2" ] || [ -f ${WAZUH_TMP_DIR}/create_conf ] ; then

        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf
        ${SCRIPTS_DIR}/add_localfiles.sh >> ${DIR}/etc/ossec.conf

    else
        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf.new
        chmod 640 ${DIR}/etc/ossec.conf.new
    fi

    # Restore /var/ossec permissions
    . ${SCRIPTS_DIR}/restore-permissions.sh

    # For the etc dir
    if [ -f /etc/localtime ]; then
        cp -pL /etc/localtime ${DIR}/etc/;
        chmod 640 ${DIR}/etc/localtime
        chown root:${GROUP} ${DIR}/etc/localtime
    fi

    # Restore the local rules, client.keys and local_decoder
    if [ -f ${WAZUH_TMP_DIR}/client.keys ]; then
        cp ${WAZUH_TMP_DIR}/client.keys ${DIR}/etc/client.keys
    fi
    # Restore ossec.conf configuration
    if [ -f ${WAZUH_TMP_DIR}/ossec.conf ]; then
        mv ${WAZUH_TMP_DIR}/ossec.conf ${DIR}/etc/ossec.conf
    fi
    # Restore internal options configuration
    if [ -f ${WAZUH_TMP_DIR}/local_internal_options.conf ]; then
        mv ${WAZUH_TMP_DIR}/local_internal_options.conf ${DIR}/etc/local_internal_options.conf
    fi

    # Install the SCA files
    if [ -d "${SCA_FILES_DIR}" ]; then

        . ${SCRIPTS_DIR}/src/init/dist-detect.sh

        if [ "${DIST_NAME}" = "debian" ]; then
            if [ "${DIST_VER}" = "9" ]; then
                DIST_VER=""
            fi
        elif [ "${DIST_NAME}" = "ubuntu" ]; then
            DIST_NAME="debian"
            DIST_VER=""
        else
            DIST_NAME="generic"
            DIST_VER=""
        fi

        CONF_ASSESMENT_DIR="${SCA_FILES_DIR}/${DIST_NAME}/${DIST_VER}"
        mkdir -p ${DIR}/ruleset/sca

        # Install the configuration files needed for this hosts
        if [ -r ${CONF_ASSESMENT_DIR}/sca.files ]; then

            for sca_file in $(cat ${CONF_ASSESMENT_DIR}/sca.files); do
                mv ${SCA_FILES_DIR}/${sca_file} ${DIR}/ruleset/sca
            done
            # Set correct permissions, owner and group
            chmod 640 ${DIR}/ruleset/sca/*
            chown root:${GROUP} ${DIR}/ruleset/sca/*
            # Delete the temporary directory
            rm -rf ${SCA_FILES_DIR}

        fi
    fi

    # logrotate configuration file
    if [ -d /etc/logrotate.d/ ]; then
        if [ -e /etc/logrotate.d/wazuh-hids ]; then
            rm -f /etc/logrotate.d/wazuh-hids
        fi
    fi

    # Restore group files
    if [ -d ${WAZUH_TMP_DIR}/group ]; then
        for file in ${WAZUH_TMP_DIR}/group/* ; do
            mv ${file} ${DIR}/etc/shared/
        done
        rm -rf ${WAZUH_TMP_DIR}/group
    fi
    chmod 660 ${DIR}/etc/shared/*
    chown -R root:ossec ${DIR}/etc/shared/
    chown root:ossec ${DIR}/logs/ossec.log ${DIR}/logs/ossec.json

    # Check if SELinux is installed and enabled
    if command -v getenforce > /dev/null 2>&1 && command -v semodule > /dev/null 2>&1; then
        if [ $(getenforce) !=  "Disabled" ]; then
            semodule -i ${DIR}/var/selinux/wazuh.pp
            semodule -e wazuh
        fi
    fi

    # Service
    if [ -f /etc/init.d/wazuh-agent ]; then
        if [ -d /run/systemd/system ]; then
          systemctl enable wazuh-agent > /dev/null 2>&1
        fi
        update-rc.d wazuh-agent defaults > /dev/null 2>&1
    fi

    # Register and configure agent if Wazuh environment variables are defined
    if [ -z "$2" ] ; then
        ${SCRIPTS_DIR}/src/init/register_configure_agent.sh > /dev/null || :
    fi

    # Delete installation scripts
    if [ -d ${SCRIPTS_DIR} ]; then
        rm -rf ${SCRIPTS_DIR}
    fi

    # Delete tmp directory
    if [ -d ${WAZUH_TMP_DIR} ]; then
        rm -rf ${WAZUH_TMP_DIR}
    fi

    # If the parent directory is empty, delete it
    if [ -z "$(ls -A ${WAZUH_GLOBAL_TMP_DIR})" ]; then
        rm -rf ${WAZUH_GLOBAL_TMP_DIR}
    fi

    if [ -s ${DIR}/etc/client.keys ]; then
        if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<server-ip>).*(?=</server-ip>)' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' > /dev/null 2>&1; then
        service wazuh-agent restart || :
        fi
        if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<server-hostname>).*(?=</server-hostname>)' > /dev/null 2>&1; then
        service wazuh-agent restart || :
        fi
        if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<address>)(?!MANAGER_IP).*(?=</address>)' > /dev/null 2>&1; then
        service wazuh-agent restart || :
        fi
    fi
    # Fix /etc/ossec-init.conf
    chmod 640 /etc/ossec-init.conf
    chown root:ossec /etc/ossec-init.conf

    ;;


    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
