#!/bin/bash
# postinst script for ossec-hids
# Wazuh, Inc 2016

set -e

case "$1" in
    configure|upgrade)

    OS=$(lsb_release -si)
	DIR="/var/ossec/api"
	OSSEC_HIDS_TMP_DIR="/tmp/wazuh-api"
    USER="ossec"
    GROUP="ossec"
	OSMYSHELL="/sbin/nologin"
    SCRIPTS_DIR="/usr/share/wazuh-api/scripts/tmp"

    if [ ! -f ${OSMYSHELL} ]; then
	    if [ -f "/bin/false" ]; then
	        OSMYSHELL="/bin/false"
	    fi
	fi

    if [ -z "$2" ]; then
        echo "======================================================================================================"
        echo "= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh  ="
        echo "======================================================================================================"
    fi

    if [ -f /var/ossec/api/node_modules/htpasswd/bin/htpasswd ] && [ ! -x /var/ossec/api/configuration/auth/htpasswd ]; then
        ln -sf /var/ossec/api/node_modules/htpasswd/bin/htpasswd /var/ossec/api/configuration/auth/htpasswd
    fi

	if [ -x /etc/init.d/wazuh-api ]; then
        update-rc.d wazuh-api defaults > /dev/null 2>&1
	fi

    # Restore local_decoders.xml configuration
    if [ -d ${OSSEC_HIDS_TMP_DIR}/configuration ]; then
        cp ${DIR}/configuration/config.js ${OSSEC_HIDS_TMP_DIR}/configuration/config.js.debnew
        cp -rp ${OSSEC_HIDS_TMP_DIR}/configuration ${DIR}/
    fi

    # Restore /var/ossec permissions
    . ${SCRIPTS_DIR}/restore-permissions.sh

    #veriy python version
    if python -V >/dev/null 2>&1; then
      python_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))' | cut -c1-3)
      if [ ! $python_version == '2.7' ]; then
         echo "Warning: Minimal supported version is 2.7"
      fi
    else
      echo "Warning: Minimal supported version is 2.7"
    fi

    # Delete tmp directory
	if [ -d ${OSSEC_HIDS_TMP_DIR} ]; then
	    rm -r ${OSSEC_HIDS_TMP_DIR}
	fi
        if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
           systemctl restart wazuh-api.service > /dev/null 2>&1
        fi
        if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then
           service wazuh-api restart > /dev/null 2>&1
        fi

    # Delete old api framework (new is included with wazuh-manager in /var/ossec/framework)
    if [ -d /var/ossec/api/framework ]; then
        rm -rf /var/ossec/api/framework
    fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
