#!/bin/sh
# postrm script for ossec-hids
# Santiago Bassett <santiago.bassett@gmail.com>
# 03/25/2014


set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
            systemctl stop wazuh-api.service
            systemctl disable wazuh-api.service
        fi

        if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then
 
           if ps axu | grep /var/ossec/api/app.js | grep -v grep; then
		service wazuh-api stop
	   fi
	   if [ -f /etc/init.d/wazuh-api ]; then
              rm /etc/init.d/wazuh-api
	   fi
        fi
        if [ -L /var/ossec/api/configuration/auth/htpasswd ]; then
	     rm /var/ossec/api/configuration/auth/htpasswd
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
