#!/bin/sh
# prerm script for Wazuh

set -e

DIR="/var/ossec"
WAZUH_API_DIR="${DIR}/api"

case "$1" in
    upgrade|deconfigure)

        if ps axu | grep ${WAZUH_API_DIR}/app.js | grep -v grep > /dev/null ; then
            if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
                systemctl stop wazuh-api.service > /dev/null 2>&1
                systemctl disable wazuh-api > /dev/null 2>&1
            fi

            if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then
                service wazuh-api stop
            fi
        fi


        # Fix for forcing the stop of the api
        if ps aux | grep ${WAZUH_API_DIR}/app.js | grep -v grep > /dev/null ; then
            kill -9 `ps -ef | grep "${WAZUH_API_DIR}/app.js" | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
        fi

    ;;



    remove)


        if ps axu | grep ${WAZUH_API_DIR}/app.js | grep -v grep > /dev/null ; then
            if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
                systemctl stop wazuh-api.service
            fi

            if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then
                service wazuh-api stop
            fi
        fi


        # Fix for forcing the stop of the api
        if ps aux | grep ${WAZUH_API_DIR}/app.js | grep -v grep > /dev/null ; then
            kill -9 `ps -ef | grep "${WAZUH_API_DIR}/app.js" | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
        fi


        # Deleting auth configuration on delete
        if [ -d ${WAZUH_API_DIR}/configuration/auth/ ]; then
            rm -rf ${WAZUH_API_DIR}/configuration/auth/
        fi


    ;;

    failed-upgrade)
    if ps axu | grep ${WAZUH_API_DIR}/app.js | grep -v grep > /dev/null ; then
        if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
            systemctl stop wazuh-api.service
        fi

        if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then
            service wazuh-api stop
        fi
    fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

exit 0
