FROM debian
RUN mkdir -p /tests
COPY bach.sh /tests/bach.sh
RUN mkdir -p /tests/unattended/
COPY unattended/test-common.sh /tests/unattended/test-common.sh
RUN mkdir -p /unattended_scripts/install_functions/opendistro/