#!/bin/sh

# Wazuh-indexer base file
# Copyright (C) 2022, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# This wrapper script allows SystemD to feed a file containing a passphrase into
# the main Wazuh-indexer startup script

if [ -n "$WI_KEYSTORE_PASSPHRASE_FILE" ] ; then
  exec /usr/share/wazuh-indexer/bin/opensearch "$@" < "$WI_KEYSTORE_PASSPHRASE_FILE"
else
  exec /usr/share/wazuh-indexer/bin/opensearch "$@"
fi