#!/bin/sh
# postinst script for Wazuh-indexer
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

set -e

export NAME=wazuh-indexer
export CONFIG_DIR="/etc/${NAME}"
export INSTALLATION_DIR="/usr/share/${NAME}"
export PID_DIR="/run/${NAME}"
export LOG_DIR="/var/log/${NAME}"

#
# This script is executed in the post-removal phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=purge     : indicates an upgrade

# Source the default env file
if [ -f "/etc/default/${NAME}" ]; then
    . "/etc/default/${NAME}"
fi

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-${CONFIG_DIR}}

REMOVE_DIRS=false
REMOVE_CONFIG_DIRECTORY=false
REMOVE_USER_AND_GROUP=false

case "$1" in

    # Debian ####################################################
    remove)
        REMOVE_DIRS=true
    ;;

    purge)
        REMOVE_DIRS=true
        REMOVE_CONFIG_DIRECTORY=true
        REMOVE_USER_AND_GROUP=true
    ;;

    failed-upgrade|abort-install|abort-upgrade|upgrade|disappear)
    ;;

    *)
        echo "post remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ "$REMOVE_DIRS" = "true" ]; then
    if [ -d "${INSTALLATION_DIR}" ]; then
        echo -n "Deleting installation directory..."
        rm -rf "${INSTALLATION_DIR}" > /dev/null 2>&1
        echo " OK"
    fi

    if [ -d "${PID_DIR}" ]; then
        echo -n "Deleting PID directory..."
        rm -rf "${PID_DIR}" > /dev/null 2>&1
        echo " OK"
    fi

    # Delete the config directory if we are purging
    if [ "$REMOVE_CONFIG_DIRECTORY" = "true" ]; then
        echo -n "Deleting configuration directory..."
        rm -rf "${CONFIG_DIR}" > /dev/null 2>&1
        echo " OK"
    fi

    # Delete the data directory if and only if empty
    if [ -d "${LOG_DIR}" ]; then
        rmdir --ignore-fail-on-non-empty "${LOG_DIR}"
    fi

    # Delete performanceanalyzer directory
    if [ -d "/dev/shm/performanceanalyzer" ]; then
        rm -rf "/dev/shm/performanceanalyzer" > /dev/null 2>&1
    fi
fi


if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
    # Remove the user if it exists
    if getent passwd "${NAME}" > /dev/null 2>&1; then
        userdel "${NAME}" > /dev/null 2>&1
    fi

    # Remove the group if it exists
    if command -v getent > /dev/null 2>&1 && getent group "${NAME}" > /dev/null 2>&1; then
        groupdel "${NAME}" > /dev/null 2>&1
    elif getent group "${NAME}" > /dev/null 2>&1; then
        groupdel "${NAME}" > /dev/null 2>&1
    fi
fi

