## Multi-node Wazuh cluster configuration

cluster.name: <wazuh-cluster>

node.type: <master|worker>

master.address: <wazuh-master-address>

bind.address: 0.0.0.0

port: 1516

hidden: no

disabled: no
