#!/bin/sh
# prerm script for wazuh-manager

set -e

DIR="/var/ossec"

case "$1" in
    upgrade|deconfigure)
      if [ -f ${DIR}/bin/ossec-control ]; then
         ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    remove)

      if [ -n "$(ps -e | grep -E ^\ *1\ .*systemd$)" ]; then
        systemctl stop wazuh-agent
      fi

      if [ -n "$(ps -e | grep -E ^\ *1\ .*init$)" ]; then
        service wazuh-agent stop
      fi

      if [ -f ${DIR}/bin/ossec-control ]; then
        ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi

      # Purging files
      if [ -d ${DIR}/queue/ ]; then
        rm -rf ${DIR}/queue/
      fi
      
      # Save the conffiles
      mkdir -p ${DIR}/tmp/conffiles

      cp -p ${DIR}/etc/client.keys ${DIR}/tmp/conffiles
      cp -p ${DIR}/etc/local_internal_options.conf ${DIR}/tmp/conffiles
      cp -p ${DIR}/etc/ossec.conf ${DIR}/tmp/conffiles
      cp -pr ${DIR}/etc/shared ${DIR}/tmp/conffiles

      if [ -d ${DIR}/etc/shared/ ]; then
        rm -rf ${DIR}/etc/shared/
      fi

    ;;

    failed-upgrade)
      if [ -f ${DIR}/bin/ossec-control ]; then
        ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
    ;;

esac

exit 0
