#!/bin/sh
# postinst script for wazuh-wui
# Wazuh, Inc 2015-2020

set -e
DIR="/"
USR_DIR="${DIR}/usr/share/wazuh-wui"
ETC_DIR="${DIR}/usr/share/wazuh-wui"

case "$1" in
    configure)
        setcap 'cap_net_bind_service=+ep' /usr/share/wazuh-wui/node/bin/node
        if [ -f ${USR_DIR}/wazuh-wui.restart ]; then
        rm -f ${USR_DIR}/wazuh-wui.restart
            if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 ; then
                systemctl restart wazuh-wui.service > /dev/null 2>&1
            elif command -v service > /dev/null 2>&1 && service wazuh-wui status 2>/dev/null | grep "running" > /dev/null 2>&1; then
                service wazuh-wui restart > /dev/null 2>&1
            fi
        fi
    ;;


    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
