#!/bin/sh
# postrm script for wazuh-wui
# Wazuh, Inc 2015-2020

set -e

DIR="/"
USR_DIR="${DIR}/usr/share/wazuh-wui"
ETC_DIR="${DIR}/usr/share/wazuh-wui"

case "$1" in
    remove|failed-upgrade|abort-install|abort-upgrade|disappear)

        if [ $1 = 0 ];then
            # Remove the wazuh-wui user if it exists
            if id -u wazuh-wui > /dev/null 2>&1; then
                userdel wazuh-wui >/dev/null 2>&1
            fi
            # Remove the wazuh-wui group if it exists
            if command -v getent > /dev/null 2>&1 && getent group wazuh-wui > /dev/null 2>&1; then
                groupdel wazuh-wui >/dev/null 2>&1
            elif id -g wazuh-wui > /dev/null 2>&1; then
                groupdel wazuh-wui >/dev/null 2>&1
            fi
        fi
        ;;

        purge)

        if getent passwd | grep -q "^wazuh-wui" ; then
            deluser wazuh-wui > /dev/null 2>&1
        fi
        if getent group | grep -q "^wazuh-wui" ; then
            delgroup wazuh-wui > /dev/null 2>&1
        fi
        rm -rf ${USR_DIR} ${ETC_DIR}

    ;;

    upgrade)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
