#!/bin/sh
# preinst script for wazuh-wui

set -e

# configuration variables
DIR="/"
USR_DIR="${DIR}/usr/share/wazuh-wui"
ETC_DIR="${DIR}/etc/wazuh-wui"


# environment configuration
if [ ! -d ${USR_DIR} ]; then
    mkdir -p ${USR_DIR}
    mkdir -p ${ETC_DIR}

else
    rm -rf ${USR_DIR}
    mkdir -p ${USR_DIR}
    rm -rf ${ETC_DIR}
    mkdir -p ${ETC_DIR}
fi

case "$1" in
    install|upgrade)
        # Create the wazuh-wui group if it doesn't exists
        if command -v getent > /dev/null 2>&1 && ! getent group wazuh-wui > /dev/null 2>&1; then
        groupadd -r wazuh-wui
        elif ! id -g wazuh-wui > /dev/null 2>&1; then
        groupadd -r wazuh-wui
        fi
        # Create the wazuh-wui user if it doesn't exists
        if ! id -u wazuh-wui > /dev/null 2>&1; then
        useradd -g wazuh-wui -G wazuh-wui -d %{_localstatedir} -r -s /sbin/nologin wazuh-wui
        fi

        # Stop the services to upgrade the package
        if [ $1 = 2 ]; then
        if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-wui > /dev/null 2>&1; then
            systemctl stop wazuh-wui.service > /dev/null 2>&1
            touch ${USR_DIR}/wazuh-wui.restart
        # Check for SysV
        elif command -v service > /dev/null 2>&1 && service wazuh-wui status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
            service wazuh-wui stop > /dev/null 2>&1
            touch ${USR_DIR}/wazuh-wui.restart
        fi
        fi
    ;;

    abort-upgrade)

    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
