#!/bin/sh
# prerm script for wazuh-manager

set -e

DIR="/"
USR_DIR="${DIR}/usr/share/wazuh-wui"
ETC_DIR="${DIR}/usr/share/wazuh-wui"

case "$1" in
    upgrade|deconfigure)

    ;;

    remove)
        if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-wui > /dev/null 2>&1; then
            systemctl stop wazuh-wui.service > /dev/null 2>&1
        # Check for SysV
        elif command -v service > /dev/null 2>&1 && service wazuh-wui status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
            service wazuh-wui stop > /dev/null 2>&1
        fi

    failed-upgrade)
        if [ -f ${DIR}/bin/wazuh-control ]; then
            ${DIR}/bin/wazuh-control stop > /dev/null 2>&1
        fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

exit 0
