DIR="PARAM_INSTALLATION_DIR"
SCRIPTS_DIR="PARAM_INSTALLATION_SCRIPTS_DIR"
SCA_BASE_DIR="${SCRIPTS_DIR}/sca"
USER="ossec"
GROUP="ossec"

common() {
    # Install the SCA files
    if [ -d "${SCA_BASE_DIR}" ]; then

        . ${SCRIPTS_DIR}/src/init/dist-detect.sh

        SCA_DIR="${DIST_NAME}/${DIST_VER}"

        SCA_TMP_DIR="${SCA_BASE_DIR}/${DIST_NAME}/${DIST_VER}"
        mkdir -p ${DIR}/ruleset/sca

        # Install the configuration files needed for this hosts
        if [ -r "${SCA_BASE_DIR}/${DIST_NAME}/${DIST_VER}/${DIST_SUBVER}/sca.files" ]; then
            SCA_TMP_DIR="${SCA_BASE_DIR}/${DIST_NAME}/${DIST_VER}/${DIST_SUBVER}"
        elif [ -r "${SCA_BASE_DIR}/${DIST_NAME}/${DIST_VER}/sca.files" ]; then
            SCA_TMP_DIR="${SCA_BASE_DIR}/${DIST_NAME}/${DIST_VER}"
        elif [ -r "${SCA_BASE_DIR}/${DIST_NAME}/sca.files" ]; then
            SCA_TMP_DIR="${SCA_BASE_DIR}/${DIST_NAME}"
        else
            SCA_TMP_DIR="${SCA_BASE_DIR}/generic"
        fi

        SCA_TMP_FILE="${SCA_TMP_DIR}/sca.files"

        if [ -r ${SCA_TMP_FILE} ]; then

            for sca_file in $(cat ${SCA_TMP_FILE}); do
                cp ${SCA_BASE_DIR}/${sca_file} ${DIR}/ruleset/sca
            done
        fi

        # Set correct permissions, owner and group
        chmod 640 ${DIR}/ruleset/sca/*
        chown root:${GROUP} ${DIR}/ruleset/sca/*

    fi

    touch ${DIR}/logs/active-responses.log
    chown ossec:ossec ${DIR}/logs/active-responses.log
    chmod 0660 ${DIR}/logs/active-responses.log

    # Register and configure agent if Wazuh environment variables are defined
    if [ -z "$2" ] ; then
        ${SCRIPTS_DIR}/src/init/register_configure_agent.sh > /dev/null || :
    fi

    # Restoring file permissions
    ${SCRIPTS_DIR}/restore-permissions.sh > /dev/null 2>&1 || :

    # Fix /etc/ossec-init.conf
    chmod 640 /etc/ossec-init.conf
    chown root:ossec /etc/ossec-init.conf
    ${SCRIPTS_DIR}/fix_owner.sh 2>/dev/null
}

post_upgrade() {
    ${SCRIPTS_DIR}/gen_ossec.sh conf agent Arch rolling > ${DIR}/etc/ossec.conf.new
    chmod 660 ${DIR}/etc/ossec.conf.new

    common
}

post_install() {
    if ! getent group | grep -q "^ossec" ; then
        systemd-sysusers
    fi

    if [ -f ${SCRIPTS_DIR}/ossec-init.conf ] ; then
        cp ${SCRIPTS_DIR}/ossec-init.conf /etc/ossec-init.conf
    fi

    ${SCRIPTS_DIR}/gen_ossec.sh conf agent Arch rolling > ${DIR}/etc/ossec.conf
    ${SCRIPTS_DIR}/add_localfiles.sh >> ${DIR}/etc/ossec.conf

    common
}
