nodes:
  # Wazuh indexer server nodes
  indexer:
    name: node-1
    ip: <indexer-node-ip>
    # name: node-2
    # ip: <elasticsearch-node-ip>
    # name: node-3
    # ip: <elasticsearch-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  wazuh_servers:
    name: wazuh-1
    ip: <wazuh-manager-ip>
    # node_type: master
    # name: wazuh-2
    # ip: <wazuh-manager-ip>
    # node_type: worker

  # Wazuh dashboard node
  dashboard:
    name: dashboard
    ip: <dashboard-node-ip>
