nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: "<indexer-node-ip>"
    - name: indexer-2
      ip: "<indexer-node-ip>"
    - name: indexer-3
      ip: "<indexer-node-ip>"
  server:
    - name: server-1
      ip: "<server-node-ip>"
      node_type: master
    - name: server-2
      ip: "<server-node-ip>"
      node_type: worker
    - name: server-3
      ip: "<server-node-ip>"
      node_type: worker
  dashboard:
    - name: dashboard-1
      ip: "<dashboard-node-ip>"
    - name: dashboard-2
      ip: "<dashboard-node-ip>"
    - name: dashboard-3
      ip: "<dashboard-node-ip>"
