#!/bin/sh
# postrm script for ossec-hids
# Wazuh, Inc 2016
set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
	if getent passwd | grep -q "^ossecr"
	then
		deluser ossecr  > /dev/null 2>&1
	fi
	if getent passwd | grep -q "^ossecm"
	then
		deluser ossecm  > /dev/null 2>&1
	fi
	if getent passwd | grep -q "^ossec"
	then
		deluser ossec  > /dev/null 2>&1
	fi
	if getent group | grep -q "^ossec"
	then
		delgroup ossec  > /dev/null 2>&1
	fi
        if [ -f /etc/init.d/wazuh-manager ]; then
          rm -f /etc/init.d/wazuh-manager
        fi
        if [ -f /etc/ossec-init.conf ]; then
          rm -f /etc/ossec-init.conf
        fi
        if [ -f /etc/logrotate.d/wazuh-hids ]; then
          rm -f /etc/logrotate.d/wazuh-hids
        fi
        if [ -f /var/ossec/etc/ossec-init.conf ]; then
          rm -f /var/ossec/etc/ossec-init.conf
        fi

	update-rc.d -f wazuh-manager remove

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
