#!/bin/sh
# preinst script for ossec-hids

set -e

# configuration variables
OSSEC_HIDS_TMP_DIR="/tmp/wazuh-manager"
DIR="/var/ossec/"

# environment configuration
if [ ! -d ${OSSEC_HIDS_TMP_DIR} ]; then
  mkdir ${OSSEC_HIDS_TMP_DIR}
fi

case "$1" in
    install|upgrade)

        if [ -z "$2" ]
        then
		if [ -f ${DIR}/etc/ossec.conf ]; then
		cp  ${DIR}/etc/ossec.conf  ${DIR}/etc/ossec.conf.deborig
		chmod 0600 ${DIR}/etc/ossec.conf.deborig
		chown root:root ${DIR}/etc/ossec.conf.deborig
                echo "====================================================================================="
                echo "= Backup from your ossec.conf has been created at /var/ossec/etc/ossec.conf.deborig ="
                echo "= Please verify your ossec.conf configuration at /var/ossec/etc/ossec.conf          ="
                echo "====================================================================================="
		fi
	fi
        # Delete old service
        if [ -f /etc/init.d/ossec ]; then
            rm /etc/init.d/ossec
        fi
        if [ -f ${DIR}/etc/client.keys ]; then
            cp -p ${DIR}/etc/client.keys ${OSSEC_HIDS_TMP_DIR}/client.keys
        fi
        if [ -f ${DIR}/etc/local_internal_options.conf ]; then
            cp -p ${DIR}/etc/local_internal_options.conf ${OSSEC_HIDS_TMP_DIR}/local_internal_options.conf
        fi
    ;;

    abort-upgrade)

    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
