#!/bin/sh
# prerm script for wazuh-manager

set -e

case "$1" in
    remove|upgrade|deconfigure)
      if [ -f /var/ossec/bin/ossec-control ]; then
         /var/ossec/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    failed-upgrade)
      if [ -f /var/ossec/bin/ossec-control ]; then
	 /var/ossec/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

exit 0
