#!/bin/sh
# prerm script for wazuh-manager

set -e

DIR="/var/ossec"

case "$1" in
    upgrade|deconfigure)
      if [ -f ${DIR}/bin/ossec-control ]; then
         ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    remove)

      if [ -f ${DIR}/bin/ossec-control ]; then
         ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi

      # Purging files
      if [ -d ${DIR}/queue/ ]; then
        rm -rf ${DIR}/queue/
      fi
      if [ -d ${DIR}/etc/shared/ ]; then
        rm -rf ${DIR}/etc/shared/
      fi

    ;;

    failed-upgrade)
      if [ -f ${DIR}/bin/ossec-control ]; then
        ${DIR}/bin/ossec-control stop > /dev/null 2>&1
      fi
    ;;

    *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
    ;;

esac

exit 0
