#!/bin/sh
# postinst script for wazuh-agent
# Wazuh, Inc 2015-2020

set -e

case "$1" in
    configure)

    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
    DIR="/var/ossec"
    USER="ossec"
    GROUP="ossec"
    WAZUH_TMP_DIR="/tmp/wazuh-agent"
    SCRIPTS_DIR="/usr/share/wazuh-agent/scripts/tmp"

    OSMYSHELL="/sbin/nologin"

    if [ ! -f ${OSMYSHELL} ]; then
        if [ -f "/bin/false" ]; then
            OSMYSHELL="/bin/false"
        fi
    fi

    if ! getent group | grep -q "^ossec" ; then
        addgroup --system ossec > /dev/null 2>&1
    fi
    if ! getent passwd | grep -q "^ossec" ; then
        adduser --system --home ${DIR} --shell ${OSMYSHELL} --ingroup ${GROUP} ${USER} > /dev/null 2>&1
    fi

    ${SCRIPTS_DIR}/gen_ossec.sh init agent ${DIR} > ${DIR}/etc/ossec-init.conf
    chown root:${GROUP} ${DIR}/etc/ossec-init.conf
    chmod 640 ${DIR}/etc/ossec-init.conf

    if [ -z "$2" ]; then

        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf
        ${SCRIPTS_DIR}/add_localfiles.sh >> ${DIR}/etc/ossec.conf

        if [ -f ${DIR}/etc/ossec.conf.deborig ]; then
            chmod +x ${DIR}/src/init/replace_manager_ip.sh
            ${DIR}/src/init/replace_manager_ip.sh ${DIR}/etc/ossec.conf.deborig ${DIR}/etc/ossec.conf
        fi
    else
        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf.new
        chmod 640 ${DIR}/etc/ossec.conf.new
    fi

    # Restore /var/ossec permissions
    . ${SCRIPTS_DIR}/restore-permissions.sh

    # For the etc dir
    if [ -f /etc/localtime ]; then
        cp -pL /etc/localtime ${DIR}/etc/;
        chmod 640 ${DIR}/etc/localtime
        chown root:${GROUP} ${DIR}/etc/localtime
    fi

    # Restore the local rules, client.keys and local_decoder
    if [ -f ${WAZUH_TMP_DIR}/client.keys ]; then
        cp ${WAZUH_TMP_DIR}/client.keys ${DIR}/etc/client.keys
    fi
    # Restore ossec.conf configuration
    if [ -f ${WAZUH_TMP_DIR}/ossec.conf ]; then
        mv ${WAZUH_TMP_DIR}/ossec.conf ${DIR}/etc/ossec.conf
    fi
    # Restore client.keys configuration
    if [ -f ${WAZUH_TMP_DIR}/local_internal_options.conf ]; then
        mv ${WAZUH_TMP_DIR}/local_internal_options.conf ${DIR}/etc/local_internal_options.conf
    fi

    # logrotate configuration file
    if [ -d /etc/logrotate.d/ ]; then
        if [ -e /etc/logrotate.d/wazuh-hids ]; then
            rm -f /etc/logrotate.d/wazuh-hids
        fi
    fi

    # Restore group files
    if [ -d ${WAZUH_TMP_DIR}/group ]; then
        for file in ${WAZUH_TMP_DIR}/group/* ; do
            mv ${file} ${DIR}/etc/shared/
        done
        rm -rf ${WAZUH_TMP_DIR}/group
        chmod 660 ${DIR}/etc/shared/*
        chown root:ossec ${DIR}/etc/shared/*
    fi

    # Check if SELinux is installed and enabled
    if command -v getenforce 2>/dev/null && command -v semodule 2>/dev/null; then
        if [ $(getenforce) !=  "Disabled" ]; then
            if ! (semodule -l | grep wazuh > /dev/null); then
            echo "Installing Wazuh policy for SELinux."
            semodule -i ${DIR}/var/selinux/wazuh.pp
            semodule -e wazuh
            else
              echo "Skipping installation of Wazuh policy for SELinux: module already installed."
            fi
        else
            echo "SELinux is disabled. Not adding Wazuh policy."
        fi
    else
        echo "SELinux is not installed. Not adding Wazuh policy."
    fi

    # Service
    if [ -f /etc/init.d/wazuh-agent ]; then
        if [ -d /run/systemd/system ]; then
          systemctl enable wazuh-agent > /dev/null 2>&1
        fi
        update-rc.d wazuh-agent defaults > /dev/null 2>&1
    fi
    if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<server-ip>).*(?=</server-ip>)' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' > /dev/null 2>&1; then
      service wazuh-agent restart || :
    fi
    if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<server-hostname>).*(?=</server-hostname>)' > /dev/null 2>&1; then
      service wazuh-agent restart || :
    fi
    if cat ${DIR}/etc/ossec.conf | grep -o -P '(?<=<address>)(?!MANAGER_IP).*(?=</address>)' > /dev/null 2>&1; then
      service wazuh-agent restart || :
    fi
    # Delete tmp directory
    if [ -d ${WAZUH_TMP_DIR} ]; then
        rm -rf ${WAZUH_TMP_DIR}
    fi

    if [ -d /usr/share/wazuh-agent ]; then
        rm -rf /usr/share/wazuh-agent
    fi

    # Fix /etc/ossec-init.conf
    chmod 640 /etc/ossec-init.conf
    chown root:ossec /etc/ossec-init.conf

    ;;


    abort-upgrade|abort-remove|abort-deconfigure)

    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
