#!/bin/sh
# postrm script for Wazuh 
# Santiago Bassett <santiago.bassett@gmail.com>
# 03/25/2014


set -e

DIR="/var/ossec"
WAZUH_API_DIR="${DIR}/api"

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)

        if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
            systemctl stop wazuh-api.service
        fi
        if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then

           if ps axu | grep ${WAZUH_API_DIR}/app.js | grep -v grep; then
        service wazuh-api stop
       fi
       if [ -f /etc/init.d/wazuh-api ]; then
              rm /etc/init.d/wazuh-api
       fi
        fi
        if [ -L ${WAZUH_API_DIR}/configuration/auth/htpasswd ]; then
         rm ${WAZUH_API_DIR}/configuration/auth/htpasswd
        fi
    ;;
    upgrade)
        if [ -n "$(ps -e | egrep ^\ *1\ .*systemd$)" ]; then
            systemctl stop wazuh-api.service
        fi

        if [ -n "$(ps -e | egrep ^\ *1\ .*init$)" ]; then

           if ps axu | grep ${WAZUH_API_DIR}/app.js | grep -v grep; then
                service wazuh-api stop
           fi
        fi
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0