#!/bin/sh
# postrm script for wazuh-agent
# Wazuh, Inc 2015-2020

set -e

DIR="/var/ossec"
WAZUH_TMP_DIR="${DIR}/packages_files/agent_config_files"

case "$1" in
    remove|failed-upgrade|abort-install|abort-upgrade|disappear)

    if [ -f /etc/logrotate.d/wazuh-hids ]; then
        rm -f /etc/logrotate.d/wazuh-hids
    fi

    if [ -f /etc/ossec-init.conf ]; then
        rm -f /etc/ossec-init.conf
    fi

    if [ -d ${WAZUH_TMP_DIR} ]; then
        rm -rf ${WAZUH_TMP_DIR}
    fi


    if [ -d /run/systemd/system ] ; then
        systemctl disable wazuh-agent > /dev/null 2>&1
        systemctl daemon-reload
        systemctl reset-failed
    fi

    update-rc.d -f wazuh-agent remove

    # Back up the old configuration files as .save
    if [ ! -d ${DIR}/etc ]; then
        mkdir -p ${DIR}/etc
    fi

    # If the directory is not empty, copy the files into ${DIR}/etc
    if [ "$(ls -A ${DIR}/tmp/conffiles)" ]; then
        mv ${DIR}/tmp/conffiles/* ${DIR}/etc
    fi
    rm -rf ${DIR}/tmp/conffiles
    rm -rf ${DIR}/tmp

    # Rename the files
    find ${DIR}/etc/ -type f -exec mv {} {}.save \;

    ;;

    purge)

    if getent passwd | grep -q "^ossec" ; then
        deluser ossec > /dev/null 2>&1
    fi
    if getent group | grep -q "^ossec" ; then
        delgroup ossec > /dev/null 2>&1
    fi
    rm -rf ${DIR}/*
    
    ;;

    upgrade)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
