#!/bin/bash
 RPM_ARCH=x86_64 
 RPM_OS=linux 
 RPM_PACKAGE_NAME=wazuh-indexer
 RPM_PACKAGE_VERSION=7.12.0 
 RPM_PACKAGE_RELEASE=1 

#
# This script is executed in the pre-installation phase
#
#   On Debian,
#       $1=install : indicates an new install
#       $1=upgrade : indicates an upgrade
#
#   On RedHat,
#       $1=1       : indicates an new install
#       $1=2       : indicates an upgrade

err_exit() {
    echo "$@" >&2
    exit 1
}

# source the default env file
if [ -f "/etc/default/wazuh-indexer" ]; then
    . "/etc/default/wazuh-indexer"
fi

export ES_PATH_CONF=${ES_PATH_CONF:-/etc/wazuh-indexer}

case "$1" in

    # Debian ####################################################
    install|upgrade)

        # Create wazuh-indexer group if not existing
        if ! getent group wazuh-indexer > /dev/null 2>&1 ; then
            echo -n "Creating wazuh-indexer group..."
            addgroup --quiet --system wazuh-indexer
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id wazuh-indexer > /dev/null 2>&1 ; then
            echo -n "Creating wazuh-indexer user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --home /nonexistent \
                    --ingroup wazuh-indexer \
                    --disabled-password \
                    --shell /bin/false \
                    wazuh-indexer
            echo " OK"
        fi
    ;;
    abort-deconfigure|abort-upgrade|abort-remove)
    ;;

    # RedHat ####################################################
    1|2)

        # Create wazuh-indexer group if not existing
        if ! getent group wazuh-indexer > /dev/null 2>&1 ; then
            echo -n "Creating wazuh-indexer group..."
            groupadd -r wazuh-indexer
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id wazuh-indexer > /dev/null 2>&1 ; then
            echo -n "Creating wazuh-indexer user..."
            useradd --system \
                    --no-create-home \
                    --home-dir /nonexistent \
                    --gid wazuh-indexer \
                    --shell /sbin/nologin \
                    --comment "wazuh-indexer user" \
                    wazuh-indexer
            echo " OK"
        fi
    ;;

    *)
        err_exit "pre install script called with unknown argument \`$1'"
    ;;
esac

