#!/bin/bash
 RPM_ARCH=x86_64 
 RPM_OS=linux 
 RPM_PACKAGE_NAME=wazuh-indexer 
 RPM_PACKAGE_VERSION=7.12.0 
 RPM_PACKAGE_RELEASE=1 

#
# This script is executed in the pre-remove phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=upgrade   : indicates an upgrade
#
#   On RedHat,
#       $1=0         : indicates a removal
#       $1=1         : indicates an upgrade

# source the default env file
if [ -f "/etc/default/wazuh-indexer" ]; then
    . "/etc/default/wazuh-indexer"
fi

export ES_PATH_CONF=${ES_PATH_CONF:-/etc/wazuh-indexer}

STOP_REQUIRED=false
REMOVE_SERVICE=false

case "$1" in

    # Debian ####################################################
    remove)
        STOP_REQUIRED=true
        REMOVE_SERVICE=true
    ;;
    upgrade)
        if [ "$RESTART_ON_UPGRADE" = "true" ]; then
            STOP_REQUIRED=true
        fi
    ;;
    deconfigure|failed-upgrade)
    ;;

    # RedHat ####################################################
    0)
        STOP_REQUIRED=true
        REMOVE_SERVICE=true
    ;;
    1)
        # Dont do anything on upgrade, because the preun script in redhat gets executed after the postinst (madness!)
    ;;

    *)
        echo "pre remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Stops the service
if [ "$STOP_REQUIRED" = "true" ]; then
    echo -n "Stopping wazuh-indexer service..."
    if command -v systemctl >/dev/null; then
        systemctl --no-reload stop wazuh-indexer.service

    elif [ -x /etc/init.d/wazuh-indexer ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d wazuh-indexer stop
        else
            /etc/init.d/wazuh-indexer stop
        fi

    # older suse linux distributions do not ship with systemd
    # but do not have an /etc/init.d/ directory
    # this tries to start the wazuh-indexer service on these
    # as well without failing this script
    elif [ -x /etc/rc.d/init.d/wazuh-indexer ] ; then
        /etc/rc.d/init.d/wazuh-indexer stop
    fi
    echo " OK"
fi

if [ -f "${ES_PATH_CONF}"/elasticsearch.keystore ]; then
  if md5sum --status -c "${ES_PATH_CONF}"/.elasticsearch.keystore.initial_md5sum; then
    rm "${ES_PATH_CONF}"/elasticsearch.keystore "${ES_PATH_CONF}"/.elasticsearch.keystore.initial_md5sum
  fi
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
        systemctl disable wazuh-indexer.service > /dev/null 2>&1 || true
    fi

    if command -v chkconfig >/dev/null; then
        chkconfig --del wazuh-indexer 2> /dev/null || true
    fi

    if command -v update-rc.d >/dev/null; then
        update-rc.d wazuh-indexer remove >/dev/null || true
    fi
fi

