#!/bin/sh
# postrm script for wazuh-agent
# Wazuh, Inc 2015-2020

set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    action="$1"
    
	if getent passwd | grep -q "^ossec" ; then
		deluser ossec > /dev/null 2>&1
	fi
	if getent group | grep -q "^ossec" ; then
		delgroup ossec > /dev/null 2>&1
	fi
    if [ -f /etc/logrotate.d/wazuh-hids ]; then
        rm -f /etc/logrotate.d/wazuh-hids
    fi

    if [ -f /etc/ossec-init.conf ]; then
        rm -f /etc/ossec-init.conf
    fi

	update-rc.d -f wazuh-agent remove

    if [ -d /run/systemd/system ] && [ "$action" != "purge" ]; then
        systemctl disable wazuh-agent > /dev/null 2>&1
        systemctl daemon-reload
        systemctl reset-failed
    fi

    ;;

    upgrade)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
