## Single-node configuration

## Elasticsearch configuration

network.host: <elasticsearch_ip>

## Certificates creation
- name: "filebeat"
  ip:
  - "<wazuh_server_ip>" 
- name: "kibana"
  ip:
  - "<kibana_ip>"     
