# Wazuh package SPEC
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
Summary:     Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
Name:        wazuh-indexer
Version:     %{_version}
Release:     %{_release}
License:     GPL
Group:       System Environment/Daemons
Source0:     %{name}-%{version}.tar.gz
URL:         https://www.wazuh.com/
BuildRoot:   %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Vendor:      Wazuh, Inc <info@wazuh.com>
Packager:    Wazuh, Inc <info@wazuh.com>
AutoReqProv: no
Requires: coreutils
ExclusiveOS: linux
BuildRequires: tar shadow-utils

# -----------------------------------------------------------------------------

%global USER %{name}
%global GROUP %{name}
%global CONFIG_DIR /etc/%{name}
%global LOG_DIR /var/log/%{name}
%global LIB_DIR /var/lib/%{name}
%global SYS_DIR /usr/lib
%global INSTALL_DIR /usr/share/%{name}
%global REPO_DIR /root/unattended_installer
%global INDEXER_FILE wazuh-indexer-base-%{version}-%{release}-linux-x64.tar.xz

# -----------------------------------------------------------------------------

%description
Wazuh indexer is a near real-time full-text search and analytics engine that gathers security-related data into one platform. This Wazuh central component indexes and stores alerts generated by the Wazuh server. Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html

# -----------------------------------------------------------------------------

%prep
# Clean BUILDROOT
rm -fr %{buildroot}

# Create package group
getent group %{GROUP} || groupadd -r %{GROUP}

# Create package user
if ! id %{USER} &> /dev/null; then
    useradd --system \
            --no-create-home \
            --home-dir %{INSTALL_DIR} \
            --gid %{GROUP} \
            --shell /sbin/nologin \
            --comment "%{USER} user" \
            %{USER}
fi

# -----------------------------------------------------------------------------

%install
# Create directories
mkdir -p ${RPM_BUILD_ROOT}%{INSTALL_DIR}
mkdir -p ${RPM_BUILD_ROOT}/etc
mkdir -p ${RPM_BUILD_ROOT}%{LOG_DIR}
mkdir -p ${RPM_BUILD_ROOT}%{LIB_DIR}
mkdir -p ${RPM_BUILD_ROOT}%{SYS_DIR}

# Set up required files
cp /tmp/%{INDEXER_FILE} ./

tar -xf %{INDEXER_FILE} && rm -f %{INDEXER_FILE}
chown -R %{USER}:%{GROUP} wazuh-indexer-*/*

# Copy base files into RPM_BUILD_ROOT directory
mv wazuh-indexer-*/etc ${RPM_BUILD_ROOT}/
mv wazuh-indexer-*%{SYS_DIR}/* ${RPM_BUILD_ROOT}%{SYS_DIR}/
rm -rf wazuh-indexer-*/etc
rm -rf wazuh-indexer-*/usr
cp -pr wazuh-indexer-*/* ${RPM_BUILD_ROOT}%{INSTALL_DIR}/

# Build wazuh-certs-tool
%{REPO_DIR}/builder.sh -c

# Build wazuh-passwords-tool
%{REPO_DIR}/builder.sh -p

# Copy the security tools
cp %{REPO_DIR}/wazuh-certs-tool.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/
cp %{REPO_DIR}/wazuh-passwords-tool.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/
cp /root/documentation-templates/wazuh/config.yml ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/config.yml

# Copy Wazuh's config files for the security plugin
cp %{REPO_DIR}/config/indexer/roles/internal_users.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security
cp %{REPO_DIR}/config/indexer/roles/roles.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security
cp %{REPO_DIR}/config/indexer/roles/roles_mapping.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security

cp /root/stack/indexer/indexer-security-init.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/bin/

chmod 750 ${RPM_BUILD_ROOT}/etc/init.d/wazuh-indexer

# -----------------------------------------------------------------------------

%pre
if [ $1 = 1 ];then # Install
    # Create package group
    getent group %{GROUP} > /dev/null 2>&1 || groupadd -r %{GROUP}

    if ! id %{USER} &> /dev/null; then
        useradd --system \
                --no-create-home \
                --home-dir %{INSTALL_DIR} \
                --gid %{GROUP} \
                --shell /sbin/nologin \
                --comment "%{USER} user" \
                %{USER} > /dev/null 2>&1
    fi
fi

# Stop the services to upgrade the package
if [ $1 = 2 ]; then
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet %{name} > /dev/null 2>&1; then
    systemctl stop %{name}.service > /dev/null 2>&1
    touch %{INSTALL_DIR}/%{name}.restart
  # Check for SysV
  elif command -v service > /dev/null 2>&1 && service %{name} status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
    service %{name} stop > /dev/null 2>&1
    touch %{INSTALL_DIR}/%{name}.restart
  elif [ -x /etc/init.d/%{name} ]; then
      if command -v invoke-rc.d >/dev/null && invoke-rc.d --quiet wazuh-indexer status > /dev/null 2>&1; then
          invoke-rc.d %{name} stop > /dev/null 2>&1
          touch %{INSTALL_DIR}/%{name}.restart
      fi

  # Older Suse linux distributions do not ship with systemd
  # but do not have an /etc/init.d/ directory
  # this tries to stop the %{name} service on these
  # as well without failing this script
  elif [ -x /etc/rc.d/init.d/%{name} ] ; then
      /etc/rc.d/init.d/%{name} stop > /dev/null 2>&1
      touch %{INSTALL_DIR}/%{name}.restart
  fi
fi

# -----------------------------------------------------------------------------

%post

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 1 ];then # Install
    echo "%{USER} hard nproc 4096" >> /etc/security/limits.conf
    echo "%{USER} soft nproc 4096" >> /etc/security/limits.conf
    echo "%{USER} hard nofile 65535" >> /etc/security/limits.conf
    echo "%{USER} soft nofile 65535" >> /etc/security/limits.conf

    # To pick up /usr/lib/sysctl.d/wazuh-indexer.conf
    if command -v systemctl > /dev/null 2>&1; then
        systemctl restart systemd-sysctl > /dev/null 2>&1 || true
    fi

fi


if [[ -d /run/systemd/system ]] ; then
    rm -f /etc/init.d/%{name}
fi

# If is an upgrade, move the securityconfig files if they exist (4.3.x versions)
if [ ${1} = 2 ]; then
    if [ -d "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig ]; then

        if [ ! -d "%{CONFIG_DIR}"/opensearch-security ]; then
            mkdir "%{CONFIG_DIR}"/opensearch-security
        fi

        cp -r "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig/* "%{CONFIG_DIR}"/opensearch-security
    fi
fi

# If is an upgrade, move the securityconfig files if they exist (4.3.x versions)
if [ ${1} = 2 ]; then
    if [ -d "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig ]; then

        if [ ! -d "%{CONFIG_DIR}"/opensearch-security ]; then
            mkdir "%{CONFIG_DIR}"/opensearch-security
        fi

        cp -r "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig/* "%{CONFIG_DIR}"/opensearch-security
    fi
fi

# -----------------------------------------------------------------------------

%preun

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 0 ];then # Remove
    echo -n "Stopping wazuh-indexer service..."
    if command -v systemctl > /dev/null 2>&1 && systemctl is-active --quiet %{name} > /dev/null 2>&1; then
        systemctl --no-reload stop %{name}.service > /dev/null 2>&1

    # Check for SysV
    elif command -v service > /dev/null 2>&1; then
        service %{name} stop > /dev/null 2>&1
    elif [ -x /etc/init.d/%{name} ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d %{name} stop > /dev/null 2>&1
        else
            /etc/init.d/%{name} stop > /dev/null 2>&1
        fi
    elif [ -x /etc/rc.d/init.d/%{name} ] ; then
        /etc/rc.d/init.d/%{name} stop > /dev/null 2>&1
    else # Anything else
        kill -15 `pgrep -f opensearch` > /dev/null 2>&1
    fi
    echo " OK"

    # Check for systemd
    if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
        systemctl disable %{name} > /dev/null 2>&1
        systemctl daemon-reload > /dev/null 2>&1
    # Check for SysV
    elif command -v service > /dev/null 2>&1 && command -v chkconfig > /dev/null 2>&1; then
        chkconfig %{name} off > /dev/null 2>&1
        chkconfig --del %{name} > /dev/null 2>&1
    fi
fi

# -----------------------------------------------------------------------------

%postun

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 0 ];then
    # Cleaning limits file
    sed -i '/%{USER}/d' /etc/security/limits.conf

    # Remove the user if it exists
    if getent passwd %{USER} > /dev/null 2>&1; then
        userdel %{USER} >/dev/null 2>&1
    fi

    # Remove the group if it exists
    if command -v getent > /dev/null 2>&1 && getent group %{GROUP} > /dev/null 2>&1; then
        groupdel %{GROUP} >/dev/null 2>&1
    elif getent group %{GROUP} > /dev/null 2>&1; then
        groupdel %{GROUP} >/dev/null 2>&1
    fi

    # Remove lingering folders and files
    if [ -d /dev/shm/performanceanalyzer ]; then
        rm -rf /dev/shm/performanceanalyzer
    fi
    rm -rf %{INSTALL_DIR}
fi

# -----------------------------------------------------------------------------

%posttrans

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ -f %{INSTALL_DIR}/%{name}.restart ]; then
    echo -n "Starting wazuh-indexer service..."
    rm -f %{INSTALL_DIR}/%{name}.restart
    if command -v systemctl > /dev/null 2>&1; then
        systemctl daemon-reload > /dev/null 2>&1
        systemctl restart %{name}.service > /dev/null 2>&1

    # Check for SysV
    elif command -v service > /dev/null 2>&1; then
        service %{name} restart > /dev/null 2>&1
    elif [ -x /etc/init.d/%{name} ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d %{name} restart > /dev/null 2>&1
        else
            /etc/init.d/%{name} restart > /dev/null 2>&1
        fi
    elif [ -x /etc/rc.d/init.d/%{name} ] ; then
        /etc/rc.d/init.d/%{name} restart > /dev/null 2>&1
    fi
    echo " OK"
fi

if [ ! -f "%{CONFIG_DIR}"/opensearch.keystore ]; then
    "%{INSTALL_DIR}"/bin/opensearch-keystore create
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/opensearch.keystore
    chmod 660 "%{CONFIG_DIR}"/opensearch.keystore
    md5sum "%{CONFIG_DIR}"/opensearch.keystore > "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
    chmod 600 "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
else
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/opensearch.keystore
    chmod 660 "%{CONFIG_DIR}"/opensearch.keystore
    if "%{INSTALL_DIR}"/bin/opensearch-keystore has-passwd --silent ; then
      echo "### Warning: unable to upgrade encrypted keystore" 1>&2
      echo " Please run opensearch-keystore upgrade and enter password" 1>&2
    else
      "%{INSTALL_DIR}"/bin/opensearch-keystore upgrade
    fi
fi

# -----------------------------------------------------------------------------

%clean
rm -fr %{buildroot}

# -----------------------------------------------------------------------------

%files
%defattr(-, %{USER}, %{GROUP})
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}
%dir %attr(750, %{USER}, %{GROUP}) %{LIB_DIR}
%dir %attr(750, %{USER}, %{GROUP}) %{LOG_DIR}

%config(noreplace) %attr(0660, root, %{GROUP}) "/etc/sysconfig/%{name}"

%config(missingok) /etc/init.d/%{name}
%attr(0640, root, root) %{SYS_DIR}/sysctl.d/%{name}.conf
%attr(0640, root, root) %{SYS_DIR}/systemd/system/%{name}.service
%attr(0640, root, root) %{SYS_DIR}/systemd/system/%{name}-performance-analyzer.service
%attr(0640, root, root) %{SYS_DIR}/tmpfiles.d/%{name}.conf


%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/NOTICE.txt
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-job-scheduler/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-job-scheduler/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-job-scheduler/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-ml/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-ml/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-ml/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-ml/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/*.jar
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/
%attr(740, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/securityadmin.sh
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/SECURITY_ADMIN_TESTS.md
%attr(740, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/audit_config_migrater.sh
%attr(740, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/hash.sh
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/NOTICE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-index-management/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/NOTICE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-neural-search/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-asynchronous-search/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-asynchronous-search/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-asynchronous-search/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-asynchronous-search/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-alerting/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-alerting/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-alerting/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-alerting/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/NOTICE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-sql/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/NOTICE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/plugin-descriptor.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-geospatial/plugin-security.policy
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-reports-scheduler/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-reports-scheduler/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-reports-scheduler/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-reports-scheduler/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-cross-cluster-replication/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-cross-cluster-replication/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-cross-cluster-replication/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/NOTICE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/plugin-descriptor.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-custom-codecs/plugin-security.policy
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/LICENSE.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/plugin-descriptor.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/NOTICE.txt
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/lib/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/lib/libopensearchknn_common.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/lib/libopensearchknn_nmslib.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/lib/libgomp.so.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-knn/lib/libopensearchknn_faiss.so
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-anomaly-detection/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-anomaly-detection/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-anomaly-detection/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-anomaly-detection/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications-core/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications-core/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications-core/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-notifications-core/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security-analytics/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security-analytics/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security-analytics/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security-analytics/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-observability/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-observability/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-observability/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-observability/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-performance-analyzer/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-performance-analyzer/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-performance-analyzer/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-performance-analyzer/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-common/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-common/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-common/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/repository-url/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/repository-url/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/repository-url/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/repository-url/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/percolator/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/percolator/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/percolator/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/search-pipeline-common/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/search-pipeline-common/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/search-pipeline-common/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/opensearch-dashboards/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/opensearch-dashboards/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/opensearch-dashboards/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-painless/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-painless/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-painless/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-painless/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/analysis-common/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/analysis-common/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/analysis-common/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/rank-eval/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/rank-eval/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/rank-eval/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/aggs-matrix-stats/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/aggs-matrix-stats/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/aggs-matrix-stats/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/geo/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/geo/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/geo/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/mapper-extras/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/mapper-extras/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/mapper-extras/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-user-agent/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-user-agent/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-user-agent/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/systemd/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/systemd/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/systemd/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/systemd/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/transport-netty4/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/transport-netty4/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/transport-netty4/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/transport-netty4/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/parent-join/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/parent-join/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/parent-join/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-mustache/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-mustache/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-mustache/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-mustache/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/GeoLite2-ASN.mmdb
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/GeoLite2-Country.mmdb
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/GeoLite2-City.mmdb
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/ingest-geoip/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/transport-netty4/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/transport-netty4/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/transport-netty4/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/parent-join/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/reindex/parent-join/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-expression/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-expression/plugin-security.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-expression/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/modules/lang-expression/plugin-descriptor.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/upgrade-cli/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/upgrade-cli/*.jar
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/plugin-cli/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/plugin-cli/*.jar
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/keystore-cli/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/tools/keystore-cli/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/lib/*.jar
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jmap.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jconsole.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jstack.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jrunscript.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jstatd.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jdb.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jinfo.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/javap.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/javadoc.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/javac.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/keytool.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/java.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jcmd.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jstat.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jhsdb.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jshell.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jps.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jfr.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jdeprscan.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jar.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jlink.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/serialver.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jmod.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/rmiregistry.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jpackage.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jdeps.1
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/man/man1/jarsigner.1
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.xml.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.management.rmi.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.attach.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.localedata.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.opt.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.naming.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.sql.rowset.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.le.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.dynalink.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jfr.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.smartcardio.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.editpad.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.security.jgss.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.crypto.cryptoki.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.nio.mapmode.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jsobject.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.incubator.vector.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.accessibility.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.compiler.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.prefs.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jdwp.agent.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.instrument.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.javadoc.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.unsupported.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.vm.compiler.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.xml.dom.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jstatd.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.jvmstat.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.security.auth.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.security.jgss.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.sql.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.management.agent.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.naming.dns.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.zipfs.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.transaction.xa.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.management.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.ed.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.incubator.foreign.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.crypto.ec.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jshell.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.xml.crypto.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jcmd.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.management.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jpackage.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.compiler.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.logging.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.se.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.unsupported.desktop.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.httpserver.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.charsets.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.datatransfer.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.naming.rmi.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.scripting.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jlink.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jartool.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.rmi.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.net.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.net.http.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.management.jfr.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.hotspot.agent.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.security.sasl.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.sctp.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jdeps.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.random.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.vm.ci.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.desktop.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/java.base.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jdi.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.jconsole.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/jmods/jdk.internal.vm.compiler.management.jmod
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/NOTICE
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/classfile_constants.h
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/linux/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/linux/jni_md.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/linux/jawt_md.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/jdwpTransport.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/jvmticmlr.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/jni.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/jvmti.h
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/include/jawt.h
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jvm.cfg
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libawt_xawt.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libawt_headless.so
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/security/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/security/blocked.certs
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/security/default.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/security/cacerts
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/security/public_suffix_list.dat
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjava.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libextnet.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjimage.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libnio.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libprefs.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjaas.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjawt.so
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jspawnhelper
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjdwp.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libawt.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/psfont.properties.ja
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libmanagement.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjsig.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/tzdb.dat
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/modules
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/server/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/server/libjsig.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/server/classes.jsa
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/server/classes_nocoops.jsa
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/server/libjvm.so
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jfr/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jfr/profile.jfc
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jfr/default.jfc
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libattach.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libdt_socket.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjsound.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/psfontj2d.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjavajpeg.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/ct.sym
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libnet.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/classlist
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libj2gss.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libmanagement_agent.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libsplashscreen.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libj2pcsc.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libverify.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/*.jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libsyslookup.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libmanagement_ext.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libj2pkcs11.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjsvml.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libsaproc.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libinstrument.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libjli.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libsctp.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libfontmanager.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/liblcms.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/librmi.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/jexec
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libzip.so
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/lib/libmlib_image.so
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/javadoc
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jmod
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jpackage
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jrunscript
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jhsdb
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jstat
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jdb
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jdeprscan
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/java
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/rmiregistry
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/javac
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jconsole
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jlink
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jfr
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jinfo
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/serialver
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jps
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jcmd
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/javap
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/keytool
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jstatd
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jstack
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jdeps
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jshell
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jimage
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jmap
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jarsigner
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/bin/jar
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/release
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.instrument/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.net/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.crypto.cryptoki/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.security.auth/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.smartcardio/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.smartcardio/pcsclite.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.zipfs/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.localedata/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.localedata/thaidict.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.prefs/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.dynalink/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.dynalink/dynalink.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jpackage/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.management/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.jvmstat/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml.crypto/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml.crypto/santuario.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.net.http/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.unsupported/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.datatransfer/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jdi/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.incubator.vector/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.charsets/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.management.jfr/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.accessibility/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jartool/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.security.sasl/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.ed/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.editpad/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.httpserver/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/c-libutl.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/icu.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/aes.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/cldr.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/public_suffix.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/ASSEMBLY_EXCEPTION
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/ADDITIONAL_LICENSE_INFO
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/asm.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/unicode.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.base/LICENSE
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jcmd/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.opt/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.opt/jopt-simple.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.scripting/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/xalan.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/bcel.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/jcup.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/xerces.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.xml/dom.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jdeps/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jstatd/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.management.agent/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.random/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.sctp/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.sql/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.nio.mapmode/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.hotspot.agent/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.attach/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.naming/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.management/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.sql.rowset/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.rmi/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.vm.compiler/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.unsupported.desktop/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.logging/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.security.jgss/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.vm.compiler.management/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jfr/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.transaction.xa/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.crypto.ec/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.vm.ci/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.naming.rmi/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.xml.dom/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.le/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.internal.le/jline.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jsobject/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jdwp.agent/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.se/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.compiler/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.incubator.foreign/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jshell/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.javadoc/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.javadoc/jquery.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.javadoc/jqueryUI.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.compiler/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.security.jgss/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jconsole/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.naming.dns/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.management.rmi/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/xwd.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/harfbuzz.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/libpng.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/jpeg.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/colorimaging.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/mesa3d.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/giflib.md
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/java.desktop/lcms.md
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/legal/jdk.jlink/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/java.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/java.security
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/limited/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/limited/exempt_local.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/limited/default_local.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/limited/default_US_export.policy
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/unlimited/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/unlimited/default_local.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/unlimited/default_US_export.policy
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/security/policy/README.txt
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/logging.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/net.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/sound.properties
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/sdp/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/sdp/sdp.conf.template
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/management/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/management/jmxremote.access
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/management/management.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/jdk/conf/management/jmxremote.password.template
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/internal_users.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/audit.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/opensearch.yml.example
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/roles.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/tenants.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/whitelist.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/action_groups.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/allowlist.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/roles_mapping.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/nodes_dn.yml
%config(noreplace) %attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-security/config.yml
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-notifications/
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-notifications/notifications.yml
%config(noreplace) %attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/jvm.options
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/jvm.options.d/
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-reports-scheduler/
%attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-reports-scheduler/reports-scheduler.yml
%config(noreplace) %attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/log4j2.properties
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-notifications-core/
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-notifications-core/notifications-core.yml
%config(noreplace) %attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch.yml
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-observability/
%attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-observability/observability.yml
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/agent-stats-metadata
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/rca_cluster_manager.conf
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/rca_idle_cluster_manager.conf
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/log4j2.xml
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/rca.conf
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/performance-analyzer.properties
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/plugin-stats-metadata
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/supervisord.conf
%attr(640, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch-performance-analyzer/opensearch_security.policy
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/agent-stats-metadata
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/rca_cluster_manager.conf
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/rca_idle_cluster_manager.conf
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/log4j2.xml
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/rca.conf
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/performance-analyzer.properties
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/plugin-stats-metadata
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/supervisord.conf
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/config/opensearch_security.policy
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/lib/
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/lib/*.jar
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/bin/
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/bin/performance-analyzer-agent
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/performance-analyzer-rca/bin/performance-analyzer-rca
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-cli
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/systemd-entrypoint
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-upgrade
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-shard
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-plugin
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-node
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-env
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-env-from-file
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-keystore
%dir %attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-performance-analyzer/
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch-performance-analyzer/performance-analyzer-agent
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/LICENSE.txt
%attr(440, %{USER}, %{GROUP}) %{INSTALL_DIR}/VERSION
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/indexer-security-init.sh
%attr(640, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/config.yml
%attr(740, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/wazuh-certs-tool.sh
%attr(740, %{USER}, %{GROUP}) %{INSTALL_DIR}/plugins/opensearch-security/tools/wazuh-passwords-tool.sh


%changelog
* Fri Dec 15 2023 support <info@wazuh.com> - 4.8.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-8-0.html
* Tue Nov 14 2023 support <info@wazuh.com> - 4.7.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-7-1.html
* Tue Nov 07 2023 support <info@wazuh.com> - 4.7.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-7-0.html
* Tue Oct 24 2023 support <info@wazuh.com> - 4.6.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-6-0.html
* Tue Oct 10 2023 support <info@wazuh.com> - 4.5.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-3.html
* Thu Aug 31 2023 support <info@wazuh.com> - 4.5.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-2.html
* Thu Aug 24 2023 support <info@wazuh.com> - 4.5.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5.1.html
* Thu Aug 10 2023 support <info@wazuh.com> - 4.5.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-0.html
* Mon Jul 10 2023 support <info@wazuh.com> - 4.4.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-5.html
* Tue Jun 13 2023 support <info@wazuh.com> - 4.4.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-4.html
* Thu May 25 2023 support <info@wazuh.com> - 4.4.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-3.html
* Mon May 08 2023 support <info@wazuh.com> - 4.4.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-2.html
* Mon Apr 17 2023 support <info@wazuh.com> - 4.4.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-1.html
* Wed Jan 18 2023 support <info@wazuh.com> - 4.4.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-0.html
* Thu Nov 10 2022 support <info@wazuh.com> - 4.3.10
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-10.html
* Mon Oct 03 2022 support <info@wazuh.com> - 4.3.9
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-9.html
* Mon Sep 19 2022 support <info@wazuh.com> - 4.3.8
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-8.html
* Mon Aug 08 2022 support <info@wazuh.com> - 4.3.7
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-7.html
* Thu Jul 07 2022 support <info@wazuh.com> - 4.3.6
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-6.html
* Wed Jun 29 2022 support <info@wazuh.com> - 4.3.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-5.html
* Tue Jun 07 2022 support <info@wazuh.com> - 4.3.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-4.html
* Tue May 31 2022 support <info@wazuh.com> - 4.3.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-3.html
* Mon May 30 2022 support <info@wazuh.com> - 4.3.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-2.html
* Wed May 18 2022 support <info@wazuh.com> - 4.3.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-1.html
* Thu May 05 2022 support <info@wazuh.com> - 4.3.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-0.html
