# Wazuh package SPEC
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
Summary:     Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
Name:        wazuh-indexer
Version:     %{_version}
Release:     %{_release}
License:     GPL
Group:       System Environment/Daemons
Source0:     %{name}-%{version}.tar.gz
URL:         https://www.wazuh.com/
BuildRoot:   %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Vendor:      Wazuh, Inc <info@wazuh.com>
Packager:    Wazuh, Inc <info@wazuh.com>
AutoReqProv: no
Requires: coreutils
ExclusiveOS: linux
BuildRequires: tar shadow-utils

# -----------------------------------------------------------------------------

%global USER %{name}
%global GROUP %{name}
%global CONFIG_DIR /etc/%{name}
%global LOG_DIR /var/log/%{name}
%global LIB_DIR /var/lib/%{name}
%global SYS_DIR /usr/lib
%global INSTALL_DIR /usr/share/%{name}
%global REPO_DIR /root/unattended_installer
%global INDEXER_FILE wazuh-indexer-base-%{version}-%{release}-linux-x64.tar.xz

# -----------------------------------------------------------------------------

%description
Wazuh indexer is a near real-time full-text search and analytics engine that gathers security-related data into one platform. This Wazuh central component indexes and stores alerts generated by the Wazuh server. Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html

# -----------------------------------------------------------------------------

%prep
# Clean BUILDROOT
rm -fr %{buildroot}

# Create package group
getent group %{GROUP} || groupadd -r %{GROUP}

# Create package user
if ! id %{USER} &> /dev/null; then
    useradd --system \
            --no-create-home \
            --home-dir %{INSTALL_DIR} \
            --gid %{GROUP} \
            --shell /sbin/nologin \
            --comment "%{USER} user" \
            %{USER}
fi

# -----------------------------------------------------------------------------

%install
# Create directories
mkdir -p ${RPM_BUILD_ROOT}%{INSTALL_DIR}
mkdir -p ${RPM_BUILD_ROOT}/etc
mkdir -p ${RPM_BUILD_ROOT}%{LOG_DIR}
mkdir -p ${RPM_BUILD_ROOT}%{LIB_DIR}
mkdir -p ${RPM_BUILD_ROOT}%{SYS_DIR}

# Set up required files
cp /tmp/%{INDEXER_FILE} ./

tar -xf %{INDEXER_FILE} && rm -f %{INDEXER_FILE}
chown -R %{USER}:%{GROUP} wazuh-indexer-*/*

# Copy base files into RPM_BUILD_ROOT directory
mv wazuh-indexer-*/etc ${RPM_BUILD_ROOT}/
mv wazuh-indexer-*%{SYS_DIR}/* ${RPM_BUILD_ROOT}%{SYS_DIR}/
rm -rf wazuh-indexer-*/etc
rm -rf wazuh-indexer-*/usr
cp -pr wazuh-indexer-*/* ${RPM_BUILD_ROOT}%{INSTALL_DIR}/

# Build wazuh-certs-tool
%{REPO_DIR}/builder.sh -c

# Build wazuh-passwords-tool
%{REPO_DIR}/builder.sh -p

# Copy the security tools
cp %{REPO_DIR}/wazuh-certs-tool.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/
cp %{REPO_DIR}/wazuh-passwords-tool.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/
cp /root/documentation-templates/wazuh/config.yml ${RPM_BUILD_ROOT}%{INSTALL_DIR}/plugins/opensearch-security/tools/config.yml

# Copy Wazuh's config files for the security plugin
cp %{REPO_DIR}/config/indexer/roles/internal_users.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security
cp %{REPO_DIR}/config/indexer/roles/roles.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security
cp %{REPO_DIR}/config/indexer/roles/roles_mapping.yml ${RPM_BUILD_ROOT}%{CONFIG_DIR}/opensearch-security

cp /root/stack/indexer/indexer-security-init.sh ${RPM_BUILD_ROOT}%{INSTALL_DIR}/bin/

chmod 750 ${RPM_BUILD_ROOT}/etc/init.d/wazuh-indexer

# -----------------------------------------------------------------------------

%pre
if [ $1 = 1 ];then # Install
    # Create package group
    getent group %{GROUP} > /dev/null 2>&1 || groupadd -r %{GROUP}

    if ! id %{USER} &> /dev/null; then
        useradd --system \
                --no-create-home \
                --home-dir %{INSTALL_DIR} \
                --gid %{GROUP} \
                --shell /sbin/nologin \
                --comment "%{USER} user" \
                %{USER} > /dev/null 2>&1
    fi
fi

# Stop the services to upgrade the package
if [ $1 = 2 ]; then
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet %{name} > /dev/null 2>&1; then
    systemctl stop %{name}.service > /dev/null 2>&1
    touch %{INSTALL_DIR}/%{name}.restart
  # Check for SysV
  elif command -v service > /dev/null 2>&1 && service %{name} status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
    service %{name} stop > /dev/null 2>&1
    touch %{INSTALL_DIR}/%{name}.restart
  elif [ -x /etc/init.d/%{name} ]; then
      if command -v invoke-rc.d >/dev/null && invoke-rc.d --quiet wazuh-indexer status > /dev/null 2>&1; then
          invoke-rc.d %{name} stop > /dev/null 2>&1
          touch %{INSTALL_DIR}/%{name}.restart
      fi

  # Older Suse linux distributions do not ship with systemd
  # but do not have an /etc/init.d/ directory
  # this tries to stop the %{name} service on these
  # as well without failing this script
  elif [ -x /etc/rc.d/init.d/%{name} ] ; then
      /etc/rc.d/init.d/%{name} stop > /dev/null 2>&1
      touch %{INSTALL_DIR}/%{name}.restart
  fi
fi

# -----------------------------------------------------------------------------

%post

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 1 ];then # Install
    echo "%{USER} hard nproc 4096" >> /etc/security/limits.conf
    echo "%{USER} soft nproc 4096" >> /etc/security/limits.conf
    echo "%{USER} hard nofile 65535" >> /etc/security/limits.conf
    echo "%{USER} soft nofile 65535" >> /etc/security/limits.conf

    # To pick up /usr/lib/sysctl.d/wazuh-indexer.conf
    if command -v systemctl > /dev/null 2>&1; then
        systemctl restart systemd-sysctl > /dev/null 2>&1 || true
    fi

fi


if [[ -d /run/systemd/system ]] ; then
    rm -f /etc/init.d/%{name}
fi

# If is an upgrade, move the securityconfig files if they exist (4.3.x versions)
if [ ${1} = 2 ]; then
    if [ -d "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig ]; then

        if [ ! -d "%{CONFIG_DIR}"/opensearch-security ]; then
            mkdir "%{CONFIG_DIR}"/opensearch-security
        fi

        cp -r "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig/* "%{CONFIG_DIR}"/opensearch-security
    fi
fi

# If is an upgrade, move the securityconfig files if they exist (4.3.x versions)
if [ ${1} = 2 ]; then
    if [ -d "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig ]; then

        if [ ! -d "%{CONFIG_DIR}"/opensearch-security ]; then
            mkdir "%{CONFIG_DIR}"/opensearch-security
        fi

        cp -r "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig/* "%{CONFIG_DIR}"/opensearch-security
    fi
fi

# -----------------------------------------------------------------------------

%preun

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 0 ];then # Remove
    echo -n "Stopping wazuh-indexer service..."
    if command -v systemctl > /dev/null 2>&1 && systemctl is-active --quiet %{name} > /dev/null 2>&1; then
        systemctl --no-reload stop %{name}.service > /dev/null 2>&1

    # Check for SysV
    elif command -v service > /dev/null 2>&1; then
        service %{name} stop > /dev/null 2>&1
    elif [ -x /etc/init.d/%{name} ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d %{name} stop > /dev/null 2>&1
        else
            /etc/init.d/%{name} stop > /dev/null 2>&1
        fi
    elif [ -x /etc/rc.d/init.d/%{name} ] ; then
        /etc/rc.d/init.d/%{name} stop > /dev/null 2>&1
    else # Anything else
        kill -15 `pgrep -f opensearch` > /dev/null 2>&1
    fi
    echo " OK"

    # Check for systemd
    if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
        systemctl disable %{name} > /dev/null 2>&1
        systemctl daemon-reload > /dev/null 2>&1
    # Check for SysV
    elif command -v service > /dev/null 2>&1 && command -v chkconfig > /dev/null 2>&1; then
        chkconfig %{name} off > /dev/null 2>&1
        chkconfig --del %{name} > /dev/null 2>&1
    fi
fi

# -----------------------------------------------------------------------------

%postun

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ $1 = 0 ];then
    # Cleaning limits file
    sed -i '/%{USER}/d' /etc/security/limits.conf

    # Remove the user if it exists
    if getent passwd %{USER} > /dev/null 2>&1; then
        userdel %{USER} >/dev/null 2>&1
    fi

    # Remove the group if it exists
    if command -v getent > /dev/null 2>&1 && getent group %{GROUP} > /dev/null 2>&1; then
        groupdel %{GROUP} >/dev/null 2>&1
    elif getent group %{GROUP} > /dev/null 2>&1; then
        groupdel %{GROUP} >/dev/null 2>&1
    fi

    # Remove lingering folders and files
    if [ -d /dev/shm/performanceanalyzer ]; then
        rm -rf /dev/shm/performanceanalyzer
    fi
    rm -rf %{INSTALL_DIR}
fi

# -----------------------------------------------------------------------------

%posttrans

export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-%{CONFIG_DIR}}

if [ -f %{INSTALL_DIR}/%{name}.restart ]; then
    echo -n "Starting wazuh-indexer service..."
    rm -f %{INSTALL_DIR}/%{name}.restart
    if command -v systemctl > /dev/null 2>&1; then
        systemctl daemon-reload > /dev/null 2>&1
        systemctl restart %{name}.service > /dev/null 2>&1

    # Check for SysV
    elif command -v service > /dev/null 2>&1; then
        service %{name} restart > /dev/null 2>&1
    elif [ -x /etc/init.d/%{name} ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d %{name} restart > /dev/null 2>&1
        else
            /etc/init.d/%{name} restart > /dev/null 2>&1
        fi
    elif [ -x /etc/rc.d/init.d/%{name} ] ; then
        /etc/rc.d/init.d/%{name} restart > /dev/null 2>&1
    fi
    echo " OK"
fi

if [ ! -f "%{CONFIG_DIR}"/opensearch.keystore ]; then
    "%{INSTALL_DIR}"/bin/opensearch-keystore create
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/opensearch.keystore
    chmod 660 "%{CONFIG_DIR}"/opensearch.keystore
    md5sum "%{CONFIG_DIR}"/opensearch.keystore > "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
    chmod 600 "%{CONFIG_DIR}"/.opensearch.keystore.initial_md5sum
else
    chown %{USER}:%{GROUP} "%{CONFIG_DIR}"/opensearch.keystore
    chmod 660 "%{CONFIG_DIR}"/opensearch.keystore
    if "%{INSTALL_DIR}"/bin/opensearch-keystore has-passwd --silent ; then
      echo "### Warning: unable to upgrade encrypted keystore" 1>&2
      echo " Please run opensearch-keystore upgrade and enter password" 1>&2
    else
      "%{INSTALL_DIR}"/bin/opensearch-keystore upgrade
    fi
fi

# -----------------------------------------------------------------------------

%clean
rm -fr %{buildroot}

# -----------------------------------------------------------------------------

%files
%defattr(-, %{USER}, %{GROUP})
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}
%dir %attr(750, %{USER}, %{GROUP}) %{LIB_DIR}
%dir %attr(750, %{USER}, %{GROUP}) %{LOG_DIR}

%config(noreplace) %attr(0660, root, %{GROUP}) "/etc/sysconfig/%{name}"

%config(missingok) /etc/init.d/%{name}
%attr(0640, root, root) %{SYS_DIR}/sysctl.d/%{name}.conf
%attr(0640, root, root) %{SYS_DIR}/systemd/system/%{name}.service
%attr(0640, root, root) %{SYS_DIR}/systemd/system/%{name}-performance-analyzer.service
%attr(0640, root, root) %{SYS_DIR}/tmpfiles.d/%{name}.conf

%config(noreplace) %attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/jvm.options
%config(noreplace) %attr(660, %{USER}, %{GROUP}) %{CONFIG_DIR}/opensearch.yml
%attr(440, %{USER}, %{GROUP}) %{INSTALL_DIR}/VERSION
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}/jvm.options.d

find "$(INSTALL_DIR)" -type d -exec chmod 750 {} \;
find "$(INSTALL_DIR)" -type f -perm 644 -exec chmod 640 {} \;
find "$(INSTALL_DIR)" -type f -perm 664 -exec chmod 660 {} \;
find "$(INSTALL_DIR)" -type f -perm 755 -exec chmod 750 {} \;
find "$(INSTALL_DIR)" -type f -perm 744 -exec chmod 740 {} \;

%changelog
* Fri Sep 08 2023 support <info@wazuh.com> - %{version}
- More info: https://documentation.wazuh.com/current/release-notes/release-4-6-0.html
* Thu Aug 31 2023 support <info@wazuh.com> - 4.5.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-2.html
* Thu Aug 24 2023 support <info@wazuh.com> - 4.5.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5.1.html
* Thu Aug 10 2023 support <info@wazuh.com> - 4.5.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-0.html
* Mon Jul 10 2023 support <info@wazuh.com> - 4.4.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-5.html
* Tue Jun 13 2023 support <info@wazuh.com> - 4.4.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-4.html
* Thu May 25 2023 support <info@wazuh.com> - 4.4.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-3.html
* Mon Apr 24 2023 support <info@wazuh.com> - 4.4.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-2.html
* Mon Apr 17 2023 support <info@wazuh.com> - 4.4.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-1.html
* Wed Jan 18 2023 support <info@wazuh.com> - 4.4.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-0.html
* Thu Nov 10 2022 support <info@wazuh.com> - 4.3.10
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-10.html
* Mon Oct 03 2022 support <info@wazuh.com> - 4.3.9
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-9.html
* Mon Sep 19 2022 support <info@wazuh.com> - 4.3.8
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-8.html
* Mon Aug 08 2022 support <info@wazuh.com> - 4.3.7
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-7.html
* Thu Jul 07 2022 support <info@wazuh.com> - 4.3.6
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-6.html
* Wed Jun 29 2022 support <info@wazuh.com> - 4.3.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-5.html
* Tue Jun 07 2022 support <info@wazuh.com> - 4.3.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-4.html
* Tue May 31 2022 support <info@wazuh.com> - 4.3.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-3.html
* Mon May 30 2022 support <info@wazuh.com> - 4.3.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-2.html
* Wed May 18 2022 support <info@wazuh.com> - 4.3.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-1.html
* Thu May 05 2022 support <info@wazuh.com> - 4.3.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-0.html
