name: 'Run shellcheck with reviewdog'
description: '🐶 Run shellcheck with reviewdog on pull requests to improve code review experience.'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: false
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: false
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `file`.
    default: 'file'
    required: false
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    required: false
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  path:
    description: "Base directory to run shellcheck. Same as `[path]` of `find` command."
    default: '.'
    required: false
  pattern:
    description: "File patterns of target files. Same as `-name [pattern]` of `find` command."
    default: '*.sh'
    required: false
  check_all_files_with_shebangs:
    description: |
      Checks all files with shebangs in the repository even if they do not match the pattern.
      Default is `false`.
    default: 'false'
    required: false
  exclude:
    description: "Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command."
    default: '*/.git/*'
    required: false
  shellcheck_flags:
    description: "Flags of shellcheck command."
    default: '--external-sources'
    required: false
runs:
  using: "composite"
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.14.0
    - run: .github/actions/shellcheck/script.sh
      shell: bash
      env:
        SHELLCHECK_VERSION: 0.8.0
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_PATTERN: ${{ inputs.pattern }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_CHECK_ALL_FILES_WITH_SHEBANGS: ${{ inputs.check_all_files_with_shebangs }}
        INPUT_SHELLCHECK_FLAGS: ${{ inputs.shellcheck_flags }}