#!/bin/sh
# postinst script for Wazuh-indexer
# Wazuh, Inc 2015-2022

export NAME=wazuh-indexer
export CONFIG_DIR=/etc/${NAME}
export INSTALLATION_DIR=/usr/share/${NAME}
export LOG_DIR=/var/log/${NAME}
export PID_DIR=/var/run/${NAME}
export LIB_DIR=/var/lib/${NAME}

#
# This script is executed in the post-removal phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=purge     : indicates an upgrade

# source the default env file
if [ -f "/etc/default/${NAME}" ]; then
    . "/etc/default/${NAME}"
fi

REMOVE_DIRS=false
REMOVE_CONFIG_DIRECTORY=false
REMOVE_DATA_DIRECTORY=false
REMOVE_USER_AND_GROUP=false

case "$1" in

    # Debian ####################################################
    remove)
        REMOVE_DIRS=true
    ;;

    purge)
        REMOVE_DIRS=true
        REMOVE_CONFIG_DIRECTORY=true
        REMOVE_DATA_DIRECTORY=true
        REMOVE_USER_AND_GROUP=true
    ;;

    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|disappear)
    ;;

    *)
        echo "post remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ "$REMOVE_DIRS" = "true" ]; then

    if [ -d ${LOG_DIR} ]; then
        echo -n "Deleting log directory..."
        rm -rf ${LOG_DIR}
        echo " OK"
    fi

    if [ -d ${INSTALLATION_DIR} ]; then
        echo -n "Deleting installation directory..."
        rm -rf ${INSTALLATION_DIR}
        echo " OK"
    fi

    if [ -d ${PID_DIR} ]; then
        echo -n "Deleting PID directory..."
        rm -rf ${PID_DIR}
        echo " OK"
    fi

    # Delete the data directory if we are purging
    if [ "${REMOVE_DATA_DIRECTORY}" = "true" ]; then
        echo -n "Deleting data directory..."
        rm -rf ${LIB_DIR}
        echo " OK"
    fi

    # Delete the config directory if we are purging
    if [ "$REMOVE_CONFIG_DIRECTORY" = "true" ]; then
        echo -n "Deleting configuration directory..."
        rm -rf ${CONFIG_DIR}
        echo " OK"
    fi

fi


if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
    if id ${NAME} > /dev/null 2>&1 ; then
        userdel ${NAME}
    fi

    if getent group ${NAME} > /dev/null 2>&1 ; then
        groupdel ${NAME}
    fi
fi

