#!/bin/sh
# postinst script for Wazuh-indexer
# Copyright (C) 2015-2022, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

export NAME=wazuh-indexer

#
# This script is executed in the pre-installation phase
#
#   On Debian,
#       $1=install : indicates an new install
#       $1=upgrade : indicates an upgrade

err_exit() {
    echo "$@" >&2
    exit 1
}

# source the default env file
if [ -f "/etc/default/wazuh-indexer" ]; then
    . "/etc/default/wazuh-indexer"
fi

case "$1" in

    # Debian ####################################################
    install|upgrade)

        # Create wazuh-indexer group if not existing
        if ! getent group ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} group..."
            addgroup --quiet --system ${NAME}
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --home /nonexistent \
                    --ingroup ${NAME} \
                    --disabled-password \
                    --shell /bin/false \
                    ${NAME}
            echo " OK"
        fi
    ;;

    abort-deconfigure|abort-upgrade|abort-remove)
    ;;

    *)
        err_exit "pre install script called with unknown argument \`$1'"
    ;;
esac

