#!/bin/bash
export NAME=wazuh-indexer

#
# This script is executed in the pre-installation phase
#
#   On Debian,
#       $1=install : indicates an new install
#       $1=upgrade : indicates an upgrade
#
#   On RedHat,
#       $1=1       : indicates an new install
#       $1=2       : indicates an upgrade

err_exit() {
    echo "$@" >&2
    exit 1
}

# source the default env file
if [ -f "/etc/default/wazuh-indexer" ]; then
    . "/etc/default/wazuh-indexer"
fi

case "$1" in

    # Debian ####################################################
    install|upgrade)

        # Create wazuh-indexer group if not existing
        if ! getent group ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} group..."
            addgroup --quiet --system ${NAME}
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --home /nonexistent \
                    --ingroup ${NAME} \
                    --disabled-password \
                    --shell /bin/false \
                    ${NAME}
            echo " OK"
        fi
    ;;
    abort-deconfigure|abort-upgrade|abort-remove)
    ;;

    # RedHat ####################################################
    1|2)

        # Create wazuh-indexer group if not existing
        if ! getent group ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} group..."
            groupadd -r ${NAME}
            echo " OK"
        fi

        # Create wazuh-indexer user if not existing
        if ! id ${NAME} > /dev/null 2>&1 ; then
            echo -n "Creating ${NAME} user..."
            useradd --system \
                    --no-create-home \
                    --home-dir /nonexistent \
                    --gid ${NAME} \
                    --shell /sbin/nologin \
                    --comment "${NAME} user" \
                    ${NAME}
            echo " OK"
        fi
    ;;

    *)
        err_exit "pre install script called with unknown argument \`$1'"
    ;;
esac

