# Because from 4.9.0 this script is migrated to a new repository, the tests of this script will not be executed.
# name: Password tool script tests
# on:
#   pull_request:
#     paths:
#       - 'unattended_installer/passwords_tool/**'

jobs:
  Build-password-tool-and-wazuh-install-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build password-tool and wazuh-install scripts
        working-directory: ./unattended_installer
        run: |
          bash builder.sh -p
          bash builder.sh -i -d staging
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: |
            unattended_installer/wazuh-install.sh
            unattended_installer/wazuh-passwords-tool.sh
          if-no-files-found: error

  test-password-tool-success:
    runs-on: ubuntu-latest
    needs: Build-password-tool-and-wazuh-install-scripts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4.1.7
        with:
          name: scripts
      - name: Install wazuh
        run: |
          sudo bash wazuh-install.sh -a -v
      - name: Uncompress wazuh install files
        run: sudo tar -xvf wazuh-install-files.tar
      - name: Run script
        run: sudo bash .github/actions/passwords-tool/tests-stack-success.sh

  test-password-tool-failure:
    runs-on: ubuntu-latest
    needs: Build-password-tool-and-wazuh-install-scripts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4.1.7
        with:
          name: scripts
      - name: Install wazuh
        run: |
          sudo bash wazuh-install.sh -a -v
      - name: Uncompress wazuh install files
        run: sudo tar -xvf wazuh-install-files.tar
      - name: Run script
        run: sudo bash .github/actions/passwords-tool/tests-stack-failure.sh
