name: Shellcheck code analysis test
on: [pull_request]

jobs:
  Shellcheck-test:
    name: Shellcheck test
    runs-on: ubuntu-latest
    needs: Get-changes
    steps:
      - uses: actions/checkout@v1
      - name: Shellcheck for libraries of artifacts
        uses: './.github/actions/shellcheck/'
        with: 
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "unattended_installer/builder.sh"
          pattern: "*.sh"
          fail_on_error: "false"
