name: Test Wazuh indexer on upgrade - Debian
on:
  push:
    branches:
      - 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
  pull_request:
    paths:
      - 'stack/indexer/deb/debian/postrm'
      - 'stack/indexer/deb/debian/postinst'
      - 'stack/indexer/deb/debian/preinst'
  workflow_dispatch:

jobs:
  Test-debian-indexer-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Download wazuh-indexer release package
        run: |
          curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
          echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee -a /etc/apt/sources.list.d/wazuh.list
          sudo apt-get update
      - name: Get the release version of Wazuh
        run: echo "RELEASE_VERSION=$(jq -r 'map(select(.prerelease == false and .draft == false)) | .[] | .tag_name' <<< $(curl --silent https://api.github.com/repos/wazuh/wazuh/releases) | sed "s|v||g" | sort -rV | head -n 1)" >> $GITHUB_ENV
      - name: Get the major and minor of the release version
        run: echo "MAJOR_MINOR=$(echo $RELEASE_VERSION | cut -d '.' -f1-2 | sed "s|\.||")" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
      - name: Build wazuh-indexer issue-branch package and set env variable
        working-directory: ./stack/indexer/deb
        run: |
          wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=12AgpaYEfEEuucCl-rKNClfHzkJ8fZFvb' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12AgpaYEfEEuucCl-rKNClfHzkJ8fZFvb" -O wazuh-indexer_4.5.0-1_amd64.deb && rm -rf /tmp/cookies.txt
          echo "PACKAGE_NAME=$(ls | grep .deb | head -n 1)" >> $GITHUB_ENV
      - name: Display env variable and move new package
        working-directory: ./stack/indexer/deb
        run: |
          echo $PACKAGE_NAME
          echo $RELEASE_VERSION
          echo $MAJOR_MINOR
          sudo cp ./$PACKAGE_NAME $GITHUB_WORKSPACE/$PACKAGE_NAME
      - name: Run script
        run: sudo bash $GITHUB_WORKSPACE/.github/actions/upgrade-indexer/upgrade-indexer.sh $GITHUB_WORKSPACE/$PACKAGE_NAME $MAJOR_MINOR