# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Required
  config.vagrant.plugins = "vagrant-reload"

  config.vm.box = "centos/7"
  config.vm.hostname = "wazuhmanager"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm_wazuh"
    vb.memory = "4096"
    vb.cpus = "4"
  end

  # Synced folder configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/tmp", type: "rsync", :rsync__exclude => ['output']

  # Provision stage
  config.vm.provision :shell, path: "provision.sh", :args => "#{ENV['WAZUH_VERSION']} #{ENV['OPENDISTRO_VERSION']}  #{ENV['ELK_VERSION']}  #{ENV['PACKAGES_REPOSITORY']} #{ENV['BRANCH']} #{ENV['BRANCHDOC']} #{ENV['DEBUG']} #{ENV['UI_REVISION']}"
  config.vm.provision :reload
  # Provision cleanup stage
  config.vm.provision :shell, path: "assets/clean.sh"
  
end
