# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "wazuhmanager"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm_wazuh"
    vb.memory = "4096"
    vb.cpus = "4"
  end
     config.vm.provision :shell, path: "provision.sh", :args => "#{ENV['WAZUH_VERSION']} #{ENV['OPENDISTRO_VERSION']}  #{ENV['ELK_VERSION']}  #{ENV['STATUS']} #{ENV['BRANCH']} -d" 
end
