#!/bin/bash
# postinst script for Wazuh
# Wazuh, Inc 2016

set -e

case "$1" in
    configure|upgrade)

    OS=$(lsb_release -si)
    DIR="/var/ossec"
    WAZUH_API_DIR="${DIR}/api"
    WAZUH_GLOBAL_TMP_DIR="${DIR}/packages_files"
    WAZUH_TMP_DIR="${WAZUH_GLOBAL_TMP_DIR}/api_config_files"
    USER="ossec"
    GROUP="ossec"
    OSMYSHELL="/sbin/nologin"
    SCRIPTS_DIR="${WAZUH_GLOBAL_TMP_DIR}/api_installation_scripts"

    if [ ! -f ${OSMYSHELL} ]; then
        if [ -f "/bin/false" ]; then
            OSMYSHELL="/bin/false"
        fi
    fi

    if [ -f ${WAZUH_API_DIR}/node_modules/htpasswd/bin/htpasswd ] && [ ! -x ${WAZUH_API_DIR}/configuration/auth/htpasswd ]; then
        ln -sf ${WAZUH_API_DIR}/node_modules/htpasswd/bin/htpasswd ${WAZUH_API_DIR}/configuration/auth/htpasswd
    fi

    # Restore local_decoders.xml configuration
    if [ -d ${WAZUH_TMP_DIR}/api/configuration ]; then
        cp ${WAZUH_API_DIR}/configuration/config.js ${WAZUH_TMP_DIR}/api/configuration/config.js.debnew
        cp -rfp ${WAZUH_TMP_DIR}/api/configuration ${WAZUH_API_DIR}/
        cp -rfp ${WAZUH_TMP_DIR}/api/configuration/auth/user ${WAZUH_API_DIR}/configuration/auth/user
        cp -rfp ${WAZUH_TMP_DIR}/api/configuration/config.js ${WAZUH_API_DIR}/configuration/config.js
    fi

    # Restore /var/ossec permissions
    if [ -f ${SCRIPTS_DIR}/restore-permissions.sh ]; then
      . ${SCRIPTS_DIR}/restore-permissions.sh
    fi

    # Remove installation scripts directory
    if [ -d ${SCRIPTS_DIR} ]; then
        rm -rf ${SCRIPTS_DIR}
    fi

    # Delete tmp directory
    if [ -d ${WAZUH_TMP_DIR} ]; then
        rm -r ${WAZUH_TMP_DIR}
    fi

    # If the parent directory is empty, delete it
    if [ -z "$(ls -A ${WAZUH_GLOBAL_TMP_DIR})" ]; then
        rm -rf ${WAZUH_GLOBAL_TMP_DIR}
    fi

    ${WAZUH_API_DIR}/scripts/install_daemon.sh > /dev/null

    # Delete old api framework (new is included with wazuh-manager in /var/ossec/framework)
    if [ -d ${WAZUH_API_DIR}/framework ]; then
        rm -rf ${WAZUH_API_DIR}/framework
    fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;


    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;

esac

exit 0
